# Generated by Django 5.2.16 on 2026-07-19 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#0F6E56', max_length=7)),
                ('accent_color', models.CharField(default='#D85A30', max_length=7)),
                ('text_color', models.CharField(default='#1A1A1A', max_length=7)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('heading_font', models.CharField(default='system-ui, sans-serif', help_text="CSS font-family value, e.g. 'Georgia, serif'", max_length=150)),
                ('body_font', models.CharField(default='system-ui, sans-serif', max_length=150)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(help_text='Which tenant this theme belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Tema del sito',
            },
        ),
    ]
