# Generated by Django 5.2.16 on 2026-07-25 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetheme',
            name='base_font_size',
            field=models.PositiveSmallIntegerField(default=16, help_text='Base body text size in px. Headings scale from this.'),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Only one theme per site can be active at a time.'),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='name',
            field=models.CharField(default='Default', help_text="Editor-facing label, e.g. 'Holiday Sale', 'Autumn Campaign'.", max_length=100),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='preview_screenshot',
            field=models.ForeignKey(blank=True, help_text='Optional thumbnail shown in the theme gallery. Not auto-generated yet.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='radius_preset',
            field=models.CharField(choices=[('flat', 'Flat'), ('soft', 'Soft'), ('sharp', 'Sharp'), ('round', 'Round')], default='soft', max_length=20),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='shadow_preset',
            field=models.CharField(choices=[('none', 'None'), ('soft', 'Soft'), ('sharp', 'Sharp'), ('lifted', 'Lifted')], default='soft', max_length=20),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='type_scale',
            field=models.CharField(choices=[('compact', 'Compact'), ('standard', 'Standard'), ('expressive', 'Expressive'), ('dramatic', 'Dramatic')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='heading_font',
            field=models.CharField(default='system-ui, sans-serif', max_length=150),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='site',
            field=models.ForeignKey(help_text='Which tenant this theme belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='wagtailcore.site'),
        ),
        migrations.AddConstraint(
            model_name='sitetheme',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('site',), name='one_active_theme_per_site'),
        ),
    ]
