# Generated by Django 5.2.16 on 2026-07-30 20:39

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitetheme_base_font_size_sitetheme_is_active_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Chatbot attivo')),
                ('title', models.CharField(blank=True, default='Chiedi ad Axatel', max_length=60, verbose_name='Titolo finestra')),
                ('welcome_message', models.TextField(blank=True, default='Ciao! Posso rispondere a domande su Axatel, le nostre soluzioni IoT e i casi di successo.', verbose_name='Messaggio di benvenuto')),
                ('placeholder', models.CharField(blank=True, default='Scrivi una domanda…', max_length=100, verbose_name='Testo segnaposto')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Chatbot',
            },
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', wagtail.fields.StreamField([('contact', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Es. 'Chiamaci'", 'max_length': 60}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Es. '+39 0444 963891'", 'max_length': 200}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': "Es. 'tel:+390444963891', 'mailto:info@axatel.it', o un URL", 'max_length': 250}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('value', 1), ('href', 2), ('external', 3)]], {})}, verbose_name='Contatti')),
                ('vat_label', models.CharField(blank=True, default='Partita IVA:', max_length=60)),
                ('vat_value', models.CharField(blank=True, max_length=60)),
                ('tax_label', models.CharField(blank=True, default='Codice Fiscale:', max_length=60)),
                ('tax_value', models.CharField(blank=True, max_length=60)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', wagtail.fields.StreamField([('link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Testo del link, es. 'Applicativi'", 'max_length': 40}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Percorso o ancora, es. '/casi' oppure '/#applicativi'", 'max_length': 200}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('label', 0), ('url', 1), ('open_in_new_tab', 2)]], {})}, help_text='Ordine e contenuto del menu principale.', verbose_name='Link del menu')),
                ('cta_label', models.CharField(blank=True, default='Parla con un esperto', max_length=60, verbose_name='Testo pulsante header')),
                ('cta_url', models.CharField(blank=True, default='/contatti', max_length=200, verbose_name='URL pulsante header')),
                ('cta_visible', models.BooleanField(default=True, verbose_name='Mostra pulsante header')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Navigazione',
            },
        ),
    ]
