# Generated by Django 5.2.16 on 2026-07-30 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chatbotsettings_footersettings_navigationsettings'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitetheme',
            name='accent_color',
            field=models.CharField(default='#EA3F30', help_text='Colore di accento per link e pulsanti.', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='background_color',
            field=models.CharField(default='#020712', help_text='Sfondo del sito. I colori strutturali si adattano automaticamente.', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='body_font',
            field=models.CharField(choices=[('Montserrat, sans-serif', 'Montserrat'), ("'Inter', sans-serif", 'Inter'), ("'Roboto', sans-serif", 'Roboto'), ("'IBM Plex Sans', sans-serif", 'IBM Plex Sans'), ('Georgia, serif', 'Georgia (serif)'), ("'JetBrains Mono', monospace", 'JetBrains Mono'), ('system-ui, sans-serif', 'System default')], default='Montserrat, sans-serif', max_length=150),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='heading_font',
            field=models.CharField(choices=[('Montserrat, sans-serif', 'Montserrat'), ("'Inter', sans-serif", 'Inter'), ("'Roboto', sans-serif", 'Roboto'), ("'IBM Plex Sans', sans-serif", 'IBM Plex Sans'), ('Georgia, serif', 'Georgia (serif)'), ("'JetBrains Mono', monospace", 'JetBrains Mono'), ('system-ui, sans-serif', 'System default')], default='Montserrat, sans-serif', max_length=150),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='preview_screenshot',
            field=models.ForeignKey(blank=True, help_text='Optional thumbnail shown in the theme gallery.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='primary_color',
            field=models.CharField(default='#C52317', help_text='Colore principale del brand.', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='radius_preset',
            field=models.CharField(choices=[('flat', 'Flat'), ('soft', 'Soft'), ('sharp', 'Sharp'), ('round', 'Round')], default='round', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='shadow_preset',
            field=models.CharField(choices=[('none', 'None'), ('soft', 'Soft'), ('sharp', 'Sharp'), ('lifted', 'Lifted')], default='lifted', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='text_color',
            field=models.CharField(default='#F2F8FF', help_text='Colore del testo principale.', max_length=7),
        ),
    ]
