# Generated by Django 5.2.16 on 2026-07-30 21:13

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sitetheme_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotsettings',
            name='suggestions',
            field=wagtail.fields.StreamField([('suggestion', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Domanda suggerita, es. 'Dove siete?'", 'max_length': 80})}, help_text="Mostrate come pulsanti cliccabili all'apertura della chat.", verbose_name='Domande suggerite'),
        ),
        migrations.AlterField(
            model_name='chatbotsettings',
            name='placeholder',
            field=models.CharField(blank=True, default='Scrivi una domanda...', max_length=100, verbose_name='Testo segnaposto'),
        ),
    ]
