# Generated by Django 5.2.16 on 2026-08-01 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chatbotsettings_suggestions_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#C52317', max_length=7, verbose_name='Colore primario')),
                ('background_color', models.CharField(default='#020712', max_length=7, verbose_name='Colore sfondo')),
                ('accent_color', models.CharField(default='#EA3F30', max_length=7, verbose_name='Colore accento')),
                ('text_color', models.CharField(default='#F2F8FF', max_length=7, verbose_name='Colore testo')),
                ('heading_font', models.CharField(default='Montserrat, sans-serif', max_length=120, verbose_name='Font titoli')),
                ('body_font', models.CharField(default='Montserrat, sans-serif', max_length=120, verbose_name='Font testo')),
                ('base_font_size', models.PositiveSmallIntegerField(default=16, verbose_name='Dimensione font base (px)')),
                ('radius_preset', models.CharField(choices=[('flat', 'Flat'), ('soft', 'Soft'), ('sharp', 'Sharp'), ('round', 'Round')], default='round', max_length=10, verbose_name='Raggio bordi')),
                ('shadow_preset', models.CharField(choices=[('none', 'None'), ('soft', 'Soft'), ('sharp', 'Sharp'), ('lifted', 'Lifted')], default='lifted', max_length=10, verbose_name='Ombra')),
                ('type_scale_preset', models.CharField(choices=[('compact', 'Compact'), ('standard', 'Standard'), ('expressive', 'Expressive'), ('dramatic', 'Dramatic')], default='standard', max_length=12, verbose_name='Scala tipografica')),
                ('previous_values', models.JSONField(blank=True, editable=False, null=True)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Tema',
            },
        ),
        migrations.DeleteModel(
            name='SiteTheme',
        ),
    ]
