# Generated by Django 5.2.17 on 2026-09-07 08:59

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contactsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationsettings',
            name='links',
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='items',
            field=wagtail.fields.StreamField([('item', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 60}), 1: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Per un link diretto senza tendina.', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "Titolo colonna, es. 'Piattaforme'", 'max_length': 60}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': "Testo del link, es. 'Sensori'", 'max_length': 60}), 5: ('wagtail.blocks.PageChooserBlock', (), {'help_text': "Preferito: collega una pagina reale del sito. L'URL resta sempre corretto anche se cambia lo slug.", 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Usa SOLO per ancore (#sezione) o link esterni. Ignorato se sopra è selezionata una pagina.', 'max_length': 200, 'required': False}), 7: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('label', 4), ('page', 5), ('custom_url', 6), ('open_in_new_tab', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.StructBlock', [[('label', 3), ('links', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'help_text': 'Aggiungi una o più colonne per un menu a tendina. Lascia vuoto per un link diretto.', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('label', 0), ('page', 1), ('custom_url', 2), ('groups', 11)]], {})}, help_text='Ordine e contenuto del menu principale, incluse le tendine.', verbose_name='Voci del menu'),
        ),
    ]
