# Generated by Django 5.2.17 on 2026-09-12 15:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_navigationsettings_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationsettings',
            name='items',
            field=wagtail.fields.StreamField([('item', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 60}), 1: ('core.api_blocks.PageChooserBlock', (), {'help_text': 'Per un link diretto senza tendina.', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "Titolo colonna, es. 'Piattaforme'", 'max_length': 60}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': "Testo del link, es. 'Applicativi'", 'max_length': 40}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': "Percorso o ancora, es. '/casi' oppure '/#applicativi'", 'max_length': 200}), 6: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('label', 4), ('url', 5), ('open_in_new_tab', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.StructBlock', [[('label', 3), ('links', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'help_text': 'Aggiungi una o più colonne per un menu a tendina. Lascia vuoto per un link diretto.', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('label', 0), ('page', 1), ('custom_url', 2), ('groups', 10)]], {})}, help_text='Ordine e contenuto del menu principale, incluse le tendine.', verbose_name='Voci del menu'),
        ),
    ]
