# Generated by Django 5.2.17 on 2026-09-13 10:50

import core.models
import django.core.validators
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_navigationsettings_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='attachment',
            field=models.FileField(blank=True, help_text='CV o documento allegato. Massimo 10 MB.', upload_to=core.models.submission_attachment_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'odt', 'rtf', 'txt'])]),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='submission_type',
            field=models.CharField(choices=[('contact', 'Richiesta di contatto'), ('candidate', 'Candidatura')], default='contact', max_length=20),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='items',
            field=wagtail.fields.StreamField([('item', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 60}), 1: ('core.api_blocks.PageChooserBlock', (), {'help_text': 'Per un link diretto senza tendina.', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "Titolo colonna, es. 'Piattaforme'", 'max_length': 60}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': "Testo del link, es. 'Sensori'", 'max_length': 60}), 5: ('core.api_blocks.PageChooserBlock', (), {'help_text': "Preferito: collega una pagina reale del sito. L'URL resta sempre corretto anche se cambia lo slug.", 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Usa SOLO per ancore (#sezione) o link esterni. Ignorato se sopra è selezionata una pagina.', 'max_length': 200, 'required': False}), 7: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('label', 4), ('page', 5), ('custom_url', 6), ('open_in_new_tab', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.StructBlock', [[('label', 3), ('links', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'help_text': 'Aggiungi una o più colonne per un menu a tendina. Lascia vuoto per un link diretto.', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('label', 0), ('page', 1), ('custom_url', 2), ('groups', 11)]], {})}, help_text='Ordine e contenuto del menu principale, incluse le tendine.', verbose_name='Voci del menu'),
        ),
    ]
