# Generated by Django 5.2.17 on 2026-09-27 18:42

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_contactsubmission_attachment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="navigationsettings",
            name="cta_label_en",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="Testo pulsante header (EN)"
            ),
        ),
        migrations.AddField(
            model_name="navigationsettings",
            name="cta_label_fr",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="Testo pulsante header (FR)"
            ),
        ),
        migrations.AlterField(
            model_name="navigationsettings",
            name="items",
            field=wagtail.fields.StreamField(
                [("item", 14)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 60}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Etichetta EN", "max_length": 60, "required": False},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Etichetta FR", "max_length": 60, "required": False},
                    ),
                    3: (
                        "core.api_blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Per un link diretto senza tendina.",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 200, "required": False},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Titolo colonna, es. 'Piattaforme'",
                            "max_length": 60,
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Testo del link, es. 'Sensori'",
                            "max_length": 60,
                        },
                    ),
                    7: (
                        "core.api_blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Preferito: collega una pagina reale del sito. L'URL resta sempre corretto anche se cambia lo slug.",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Usa SOLO per ancore (#sezione) o link esterni. Ignorato se sopra è selezionata una pagina.",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "required": False},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 6),
                                ("label_en", 1),
                                ("label_fr", 2),
                                ("page", 7),
                                ("custom_url", 8),
                                ("open_in_new_tab", 9),
                            ]
                        ],
                        {},
                    ),
                    11: ("wagtail.blocks.ListBlock", (10,), {}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 5),
                                ("label_en", 1),
                                ("label_fr", 2),
                                ("links", 11),
                            ]
                        ],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ListBlock",
                        (12,),
                        {
                            "help_text": "Aggiungi una o più colonne per un menu a tendina. Lascia vuoto per un link diretto.",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 0),
                                ("label_en", 1),
                                ("label_fr", 2),
                                ("page", 3),
                                ("custom_url", 4),
                                ("groups", 13),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Ordine e contenuto del menu principale, incluse le tendine.",
                verbose_name="Voci del menu",
            ),
        ),
    ]
