# Generated by Django 5.2.17 on 2026-09-27 19:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_add_english_french_locales"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navigationsettings",
            name="items",
            field=wagtail.fields.StreamField(
                [("item", 15)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 60}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Etichetta EN", "max_length": 60, "required": False},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Etichetta FR", "max_length": 60, "required": False},
                    ),
                    3: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Togli la spunta per nascondere questa voce dal sito senza cancellarla.",
                            "label": "Visibile",
                            "required": False,
                        },
                    ),
                    4: (
                        "core.api_blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Per un link diretto senza tendina.",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 200, "required": False},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Titolo colonna, es. 'Piattaforme'",
                            "max_length": 60,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Testo del link, es. 'Sensori'",
                            "max_length": 60,
                        },
                    ),
                    8: (
                        "core.api_blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Preferito: collega una pagina reale del sito. L'URL resta sempre corretto anche se cambia lo slug.",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Usa SOLO per ancore (#sezione) o link esterni. Ignorato se sopra è selezionata una pagina.",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "required": False},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 7),
                                ("label_en", 1),
                                ("label_fr", 2),
                                ("visible", 3),
                                ("page", 8),
                                ("custom_url", 9),
                                ("open_in_new_tab", 10),
                            ]
                        ],
                        {},
                    ),
                    12: ("wagtail.blocks.ListBlock", (11,), {}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 6),
                                ("label_en", 1),
                                ("label_fr", 2),
                                ("visible", 3),
                                ("links", 12),
                            ]
                        ],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.ListBlock",
                        (13,),
                        {
                            "help_text": "Aggiungi una o più colonne per un menu a tendina. Lascia vuoto per un link diretto.",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 0),
                                ("label_en", 1),
                                ("label_fr", 2),
                                ("visible", 3),
                                ("page", 4),
                                ("custom_url", 5),
                                ("groups", 14),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Ordine e contenuto del menu principale, incluse le tendine.",
                verbose_name="Voci del menu",
            ),
        ),
    ]
