# Generated by Django 5.2.17 on 2026-09-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_menu_visible_switch"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactsubmission",
            name="details",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Prodotto o soluzione, tipo di opera, siti, tempistiche.",
                verbose_name="Dettagli preventivo",
            ),
        ),
        migrations.AlterField(
            model_name="contactsubmission",
            name="submission_type",
            field=models.CharField(
                choices=[
                    ("contact", "Richiesta di contatto"),
                    ("candidate", "Candidatura"),
                    ("quote", "Richiesta di preventivo"),
                ],
                default="contact",
                max_length=20,
            ),
        ),
    ]
