# Generated by Django 5.2.17 on 2026-09-29 20:03

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_quote_requests"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="Nome e cognome"),
                ),
                (
                    "role",
                    models.CharField(blank=True, max_length=120, verbose_name="Ruolo"),
                ),
                (
                    "role_en",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Ruolo (EN)"
                    ),
                ),
                (
                    "role_fr",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Ruolo (FR)"
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, max_length=600, verbose_name="Descrizione"
                    ),
                ),
                (
                    "bio_en",
                    models.TextField(
                        blank=True, max_length=600, verbose_name="Descrizione (EN)"
                    ),
                ),
                (
                    "bio_fr",
                    models.TextField(
                        blank=True, max_length=600, verbose_name="Descrizione (FR)"
                    ),
                ),
                (
                    "visible",
                    models.BooleanField(
                        default=True,
                        help_text="Spegni per nascondere la persona dal sito senza cancellarla.",
                        verbose_name="Visibile",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Meglio quadrata, almeno 400×400 px. Viene ritagliata al centro.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Foto",
                    ),
                ),
                (
                    "setting",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="core.teamsettings",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
