# Generated by Django 5.2.17 on 2026-10-03 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_team_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="department",
            field=models.CharField(
                blank=True,
                help_text="Solo per i responsabili: nome del reparto che guidano, es. 'Tecnico'. Le persone che riportano a loro fanno parte di quel reparto.",
                max_length=80,
                verbose_name="Guida il reparto",
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="department_en",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="Reparto (EN)"
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="department_fr",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="Reparto (FR)"
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="reports_to",
            field=models.ForeignKey(
                blank=True,
                help_text="La persona a cui risponde (es. il responsabile del reparto, o il CEO). Vuoto = in cima all'organigramma. Una persona appena aggiunta compare in questo elenco dopo il primo salvataggio.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_reports",
                to="core.teammember",
                verbose_name="Riporta a",
            ),
        ),
    ]
