# Generated by Django 5.2.17 on 2026-10-03 12:00

import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_teammember_department_teammember_department_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="also_reports_to",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="Facoltativo: altri responsabili di questa persona. Sulla pagina compare una linea più sottile verso ciascuno.",
                related_name="dotted_reports",
                to="core.teammember",
                verbose_name="Riporta anche a",
            ),
        ),
        migrations.AddField(
            model_name="teamsettings",
            name="label_mode",
            field=models.CharField(
                choices=[
                    ("department", "Reparto (solo sotto i responsabili)"),
                    ("role", "Ruolo (sotto ogni persona)"),
                    ("both", "Ruolo e reparto"),
                    ("none", "Nessuna etichetta"),
                ],
                default="department",
                help_text="Cosa evidenziare sotto ogni persona nell'organigramma.",
                max_length=20,
                verbose_name="Etichetta sotto il nome",
            ),
        ),
    ]
