# Generated by Django 5.2.17 on 2026-10-03 12:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_team_matrix_and_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navigationsettings",
            name="items",
            field=wagtail.fields.StreamField(
                [("item", 16)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 60}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Etichetta EN", "max_length": 60, "required": False},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Etichetta FR", "max_length": 60, "required": False},
                    ),
                    3: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Togli la spunta per nascondere questa voce dal sito senza cancellarla.",
                            "label": "Visibile",
                            "required": False,
                        },
                    ),
                    4: (
                        "core.api_blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Per un link diretto senza tendina.",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 200, "required": False},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Titolo colonna, es. 'Piattaforme'",
                            "max_length": 60,
                        },
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Automatica"),
                                ("1", "Colonna 1 (sinistra)"),
                                ("2", "Colonna 2"),
                                ("3", "Colonna 3"),
                            ],
                            "help_text": "Dove sta il gruppo nel menu a tendina (da computer). Automatica = sotto la colonna più corta. Più gruppi nella stessa colonna stanno uno sotto l'altro, nell'ordine dell'elenco.",
                            "label": "Colonna",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Testo del link, es. 'Sensori'",
                            "max_length": 60,
                        },
                    ),
                    9: (
                        "core.api_blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Preferito: collega una pagina reale del sito. L'URL resta sempre corretto anche se cambia lo slug.",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Usa SOLO per ancore (#sezione) o link esterni. Ignorato se sopra è selezionata una pagina.",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "required": False},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 8),
                                ("label_en", 1),
                                ("label_fr", 2),
                                ("visible", 3),
                                ("page", 9),
                                ("custom_url", 10),
                                ("open_in_new_tab", 11),
                            ]
                        ],
                        {},
                    ),
                    13: ("wagtail.blocks.ListBlock", (12,), {}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 6),
                                ("label_en", 1),
                                ("label_fr", 2),
                                ("visible", 3),
                                ("column", 7),
                                ("links", 13),
                            ]
                        ],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.ListBlock",
                        (14,),
                        {
                            "help_text": "Aggiungi una o più colonne per un menu a tendina. Lascia vuoto per un link diretto.",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 0),
                                ("label_en", 1),
                                ("label_fr", 2),
                                ("visible", 3),
                                ("page", 4),
                                ("custom_url", 5),
                                ("groups", 15),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Ordine e contenuto del menu principale, incluse le tendine.",
                verbose_name="Voci del menu",
            ),
        ),
    ]
