# Generated by Django 5.2.17 on 2026-10-03 20:19

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_nav_group_column"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="footersettings",
            name="social",
            field=wagtail.fields.StreamField(
                [("social", 4)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("linkedin", "LinkedIn"),
                                ("facebook", "Facebook"),
                                ("instagram", "Instagram"),
                                ("youtube", "YouTube"),
                                ("x", "X (Twitter)"),
                                ("other", "Altro"),
                            ],
                            "label": "Social",
                        },
                    ),
                    1: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Indirizzo della pagina"},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Vuoto = il nome del social (es. 'Facebook').",
                            "label": "Nome mostrato",
                            "max_length": 40,
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "label": "Visibile", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("network", 0), ("url", 1), ("label", 2), ("visible", 3)]],
                        {},
                    ),
                },
                help_text="Mostrati nel footer sotto 'Seguici'. Spegni 'Visibile' per nasconderne uno.",
                verbose_name="Seguici (social)",
            ),
        ),
        migrations.AlterField(
            model_name="contactsubmission",
            name="submission_type",
            field=models.CharField(
                choices=[
                    ("contact", "Richiesta di contatto"),
                    ("candidate", "Candidatura"),
                    ("quote", "Richiesta di preventivo"),
                    ("partner", "Proposta di collaborazione"),
                ],
                default="contact",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BrandingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "header_wing",
                    models.ForeignKey(
                        blank=True,
                        help_text="Il disegno accanto al titolo in cima alle pagine e nella citazione della home. PNG trasparente.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Ala nelle intestazioni",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nel menu in alto e nell'animazione a particelle della home. SVG o PNG trasparente.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "particle_logo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Facoltativo: un'altra versione del logo solo per le particelle. Vuoto = il logo qui sopra.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Logo per l'animazione a particelle",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Logo e immagini del sito",
            },
        ),
    ]
