# Generated by Django 5.2.17 on 2026-10-04 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_site_corrections"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactsubmission",
            name="consent_text",
            field=models.CharField(
                blank=True,
                help_text="La frase accettata e l'indirizzo dell'informativa in quel momento.",
                max_length=400,
                verbose_name="Testo del consenso",
            ),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="language",
            field=models.CharField(
                default="it", max_length=5, verbose_name="Lingua del sito"
            ),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="notified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Notifica inviata il"
            ),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="notify_error",
            field=models.TextField(blank=True, verbose_name="Errore di invio"),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="privacy_consent",
            field=models.BooleanField(default=False, verbose_name="Consenso privacy"),
        ),
        migrations.AddField(
            model_name="footersettings",
            name="cookie_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Linkata nel footer.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Pagina Cookie policy",
            ),
        ),
        migrations.AddField(
            model_name="footersettings",
            name="privacy_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Linkata nel footer e accanto alla casella del consenso in ogni modulo.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Pagina Privacy policy",
            ),
        ),
        migrations.CreateModel(
            name="FormNotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emails_contact",
                    models.TextField(
                        blank=True,
                        help_text="Un indirizzo e-mail per riga. Vuoto = gli indirizzi di ADMIN_EMAILS nel file .env del server.",
                        verbose_name="Richieste di contatto",
                    ),
                ),
                (
                    "emails_quote",
                    models.TextField(
                        blank=True,
                        help_text="Un indirizzo per riga. Vuoto = come Richieste di contatto.",
                        verbose_name="Richieste di preventivo",
                    ),
                ),
                (
                    "emails_candidate",
                    models.TextField(
                        blank=True,
                        help_text="Un indirizzo per riga. Vuoto = come Richieste di contatto.",
                        verbose_name="Candidature (CV)",
                    ),
                ),
                (
                    "emails_partner",
                    models.TextField(
                        blank=True,
                        help_text="Un indirizzo per riga. Vuoto = come Richieste di contatto.",
                        verbose_name="Proposte di collaborazione",
                    ),
                ),
                (
                    "attach_files",
                    models.BooleanField(
                        default=True,
                        help_text="Il CV o il documento inviato dal visitatore viene allegato alla notifica.",
                        verbose_name="Allega i documenti all'e-mail",
                    ),
                ),
                (
                    "send_confirmation",
                    models.BooleanField(
                        default=True,
                        help_text="Un'e-mail che conferma la ricezione, nella lingua del sito usata dal visitatore.",
                        verbose_name="Invia una conferma al visitatore",
                    ),
                ),
                (
                    "confirmation_it",
                    models.TextField(
                        blank=True,
                        default="Gentile {nome},\n\ngrazie per averci scritto: abbiamo ricevuto la tua richiesta e ti risponderemo il prima possibile, di solito entro due giorni lavorativi.\n\nIl team Axatel",
                        help_text="{nome} viene sostituito con il nome del visitatore.",
                        verbose_name="Testo della conferma (IT)",
                    ),
                ),
                (
                    "confirmation_en",
                    models.TextField(
                        blank=True,
                        default="Dear {nome},\n\nthank you for writing to us: we have received your request and will reply as soon as possible, usually within two working days.\n\nThe Axatel team",
                        verbose_name="Testo della conferma (EN)",
                    ),
                ),
                (
                    "confirmation_fr",
                    models.TextField(
                        blank=True,
                        default="Bonjour {nome},\n\nmerci de nous avoir écrit : nous avons bien reçu votre demande et vous répondrons au plus vite, en général sous deux jours ouvrés.\n\nL'équipe Axatel",
                        verbose_name="Testo della conferma (FR)",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notifiche moduli",
            },
        ),
    ]
