# Generated by Django 5.2.17 on 2026-10-04 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_form_notifications_and_consent"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchEngineSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allow_indexing",
                    models.BooleanField(
                        default=False,
                        help_text="Accendilo solo quando il sito è online sul dominio definitivo (axatel.it) e i vecchi indirizzi sono reindirizzati. Spento = 'noindex' su ogni pagina e robots.txt che blocca tutto. Sull'indirizzo IP del server il sito non è mai indicizzato.",
                        verbose_name="Consenti ai motori di ricerca di indicizzare il sito",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Motori di ricerca",
            },
        ),
    ]
