# Generated by Django 5.2.17 on 2026-10-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_search_engine_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactsubmission",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
