# Generated by Django 5.2.17 on 2026-10-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_contact_email_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbotsettings",
            name="hint_delay",
            field=models.PositiveSmallIntegerField(
                default=20,
                help_text="Tempo sulla pagina prima che compaia la nuvoletta (minimo 5).",
                verbose_name="Dopo quanti secondi",
            ),
        ),
        migrations.AddField(
            model_name="chatbotsettings",
            name="hint_excluded",
            field=models.TextField(
                blank=True,
                default="/contatti\n/privacy-policy\n/cookie-policy",
                help_text="Un indirizzo per riga (anche l'inizio di un indirizzo, es. /azienda). Vale in tutte le lingue.",
                verbose_name="Pagine senza nuvoletta",
            ),
        ),
        migrations.AddField(
            model_name="chatbotsettings",
            name="hint_text_en",
            field=models.CharField(
                blank=True,
                default="Would you like to know more about {title}?",
                max_length=160,
                verbose_name="Testo della nuvoletta (EN)",
            ),
        ),
        migrations.AddField(
            model_name="chatbotsettings",
            name="hint_text_fr",
            field=models.CharField(
                blank=True,
                default="Vous voulez en savoir plus sur {title} ?",
                max_length=160,
                verbose_name="Testo della nuvoletta (FR)",
            ),
        ),
        migrations.AddField(
            model_name="chatbotsettings",
            name="hint_text_it",
            field=models.CharField(
                blank=True,
                default="Vuoi saperne di più su {title}?",
                help_text="{title} = il nome della pagina. Sulle pagine senza nome (homepage, elenchi) si usa un testo generico.",
                max_length=160,
                verbose_name="Testo della nuvoletta (IT)",
            ),
        ),
        migrations.AddField(
            model_name="chatbotsettings",
            name="hints_enabled",
            field=models.BooleanField(
                default=True,
                help_text='Dopo qualche secondo su una pagina, una nuvoletta sopra il pulsante della chat propone domande su quella pagina. Al massimo una volta per pagina; chi preme "No grazie" non la rivede per tutta la visita.',
                verbose_name="Suggerimenti sulla pagina",
            ),
        ),
    ]
