# Generated by Django 5.2.17 on 2026-10-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_chatbot_page_hints"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbotsettings",
            name="unclear_reply_en",
            field=models.TextField(
                blank=True,
                default='I didn\'t understand the question. Could you write it with a few more words? For example: "How do you monitor landslides?"',
                verbose_name="Risposta a una domanda non chiara (EN)",
            ),
        ),
        migrations.AddField(
            model_name="chatbotsettings",
            name="unclear_reply_fr",
            field=models.TextField(
                blank=True,
                default="Je n'ai pas compris la question. Pouvez-vous l'écrire avec quelques mots de plus ? Par exemple : « Comment surveillez-vous les glissements de terrain ? »",
                verbose_name="Risposta a una domanda non chiara (FR)",
            ),
        ),
        migrations.AddField(
            model_name="chatbotsettings",
            name="unclear_reply_it",
            field=models.TextField(
                blank=True,
                default="Non ho capito la domanda. Puoi scriverla con qualche parola in più? Per esempio: «Come monitorate le frane?»",
                help_text='Per messaggi senza senso o troppo vaghi ("uff", "ok", lettere a caso, una parola che il chatbot non conosce). Vuoto = testo predefinito. Li trovi in Domande dei visitatori come "Domanda non chiara".',
                verbose_name="Risposta a una domanda non chiara (IT)",
            ),
        ),
    ]
