# Generated by Django 5.2.17 on 2026-10-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_chatbot_unclear_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="footersettings",
            name="cookie_notice_en",
            field=models.TextField(
                blank=True, max_length=300, verbose_name="Testo dell'avviso (EN)"
            ),
        ),
        migrations.AddField(
            model_name="footersettings",
            name="cookie_notice_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Barra informativa in basso alla prima visita, con il link alla Cookie policy e il pulsante OK.",
                verbose_name="Mostra l'avviso sui cookie",
            ),
        ),
        migrations.AddField(
            model_name="footersettings",
            name="cookie_notice_fr",
            field=models.TextField(
                blank=True, max_length=300, verbose_name="Testo dell'avviso (FR)"
            ),
        ),
        migrations.AddField(
            model_name="footersettings",
            name="cookie_notice_it",
            field=models.TextField(
                blank=True,
                help_text='Vuoto = "Questo sito usa solo cookie tecnici, necessari al suo funzionamento."',
                max_length=300,
                verbose_name="Testo dell'avviso (IT)",
            ),
        ),
    ]
