# Generated by Django 5.2.18 on 2026-10-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_cookie_notice"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbotsettings",
            name="contact_button",
            field=models.BooleanField(
                default=True,
                help_text="Quando il chatbot non sa rispondere, o si chiede di prezzi e preventivi, propone il modulo di contatto.",
                verbose_name='Pulsante "Parla con un esperto"',
            ),
        ),
        migrations.AddField(
            model_name="chatbotsettings",
            name="contact_path",
            field=models.CharField(
                blank=True,
                default="/contatti",
                help_text="Indirizzo in italiano, es. /contatti (vale anche per /en e /fr).",
                max_length=200,
                verbose_name="Pagina del pulsante",
            ),
        ),
        migrations.AddField(
            model_name="chatbotsettings",
            name="page_text_answers",
            field=models.BooleanField(
                default=True,
                help_text='Oltre alla descrizione breve, il chatbot risponde con il paragrafo della pagina che parla di ciò che è stato chiesto, e propone "Dimmi di più" per continuare.',
                verbose_name="Risposte dal testo delle pagine",
            ),
        ),
        migrations.AddField(
            model_name="chatbotsettings",
            name="related_pages",
            field=models.BooleanField(
                default=True,
                help_text='Sotto una risposta, fino a due pulsanti verso argomenti vicini (es. dopo "frane": "Monitoraggio fiumi").',
                verbose_name="Proponi pagine correlate",
            ),
        ),
    ]
