# Generated by Django 5.2.16 on 2026-08-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField(help_text='Una domanda o un modo di chiederla per riga. Più righe aumentano le probabilità che il chatbot la riconosca (es. una versione in italiano e una in inglese).', verbose_name='Domande')),
                ('answer', models.TextField(help_text='La risposta che il chatbot invia quando riconosce una di queste domande. Solo testo semplice, senza formattazione.', verbose_name='Risposta')),
                ('is_fallback', models.BooleanField(default=False, help_text="Attiva SOLO su una voce: la risposta usata quando nessuna domanda corrisponde abbastanza bene alle altre voci. Se provi ad attivarla su una seconda voce, il salvataggio darà errore - disattivala prima sull'altra.", verbose_name='Risposta di riserva')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Voce chatbot',
                'verbose_name_plural': 'Voci chatbot',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_fallback', True)), fields=('is_fallback',), name='unique_chatbot_fallback')],
            },
        ),
    ]
