# Generated by Django 5.2.17 on 2026-10-03 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbotentry",
            name="answer_en",
            field=models.TextField(
                blank=True,
                help_text="Per chi visita il sito in inglese. Vuoto = risposta in italiano. `manage.py translate_settings` la riempie con il modello di traduzione: rileggila.",
                verbose_name="Risposta (EN)",
            ),
        ),
        migrations.AddField(
            model_name="chatbotentry",
            name="answer_fr",
            field=models.TextField(blank=True, verbose_name="Risposta (FR)"),
        ),
        migrations.CreateModel(
            name="ChatbotQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=300, verbose_name="Domanda")),
                (
                    "language",
                    models.CharField(default="it", max_length=5, verbose_name="Lingua"),
                ),
                ("score", models.FloatField(default=0, verbose_name="Somiglianza")),
                (
                    "margin",
                    models.FloatField(default=0, verbose_name="Distacco dalla seconda"),
                ),
                (
                    "answered",
                    models.BooleanField(
                        default=False,
                        help_text="No = è stata data la risposta di riserva.",
                        verbose_name="Risposto",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Quando"),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="chatbot.chatbotentry",
                        verbose_name="Risposta usata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domanda al chatbot",
                "verbose_name_plural": "Domande al chatbot",
                "ordering": ["-created_at"],
            },
        ),
    ]
