# Generated by Django 5.2.17 on 2026-10-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_translated_answers_and_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbotquestion",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="Pagina da cui è presa la risposta, quando non è una Voce chatbot.",
                max_length=200,
                verbose_name="Risposta dal sito",
            ),
        ),
    ]
