# Generated by Django 5.2.17 on 2026-10-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_question_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatbotHint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="Come appare nel sito in italiano, es. /monitoraggio/frane (vale anche per /en e /fr).",
                        max_length=200,
                        unique=True,
                        verbose_name="Indirizzo della pagina",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Attivo")),
                (
                    "text_it",
                    models.CharField(max_length=160, verbose_name="Testo (IT)"),
                ),
                (
                    "text_en",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Testo (EN)"
                    ),
                ),
                (
                    "text_fr",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Testo (FR)"
                    ),
                ),
                (
                    "questions_it",
                    models.TextField(
                        blank=True,
                        help_text="Una per riga, al massimo 3. Scrivile come le scriverebbe un visitatore: il chatbot risponde come se le avesse digitate. Vuoto = le domande automatiche della pagina.",
                        verbose_name="Domande proposte (IT)",
                    ),
                ),
                (
                    "questions_en",
                    models.TextField(blank=True, verbose_name="Domande proposte (EN)"),
                ),
                (
                    "questions_fr",
                    models.TextField(blank=True, verbose_name="Domande proposte (FR)"),
                ),
            ],
            options={
                "verbose_name": "Suggerimento del chatbot",
                "verbose_name_plural": "Suggerimenti del chatbot",
                "ordering": ["path"],
            },
        ),
        migrations.AddField(
            model_name="chatbotquestion",
            name="from_hint",
            field=models.BooleanField(
                default=False,
                help_text="Domanda scelta nella nuvoletta di suggerimento della pagina.",
                verbose_name="Dalla nuvoletta",
            ),
        ),
    ]
