# Generated by Django 5.2.18 on 2026-10-10 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0004_page_hints"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatbotVector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=40, unique=True)),
                ("vector", models.BinaryField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Vettore chatbot",
            },
        ),
        migrations.AlterModelOptions(
            name="chatbotquestion",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Domanda ricevuta",
                "verbose_name_plural": "Domande ricevute",
            },
        ),
        migrations.AddField(
            model_name="chatbotentry",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Spegni per non usare più questa risposta senza cancellarla.",
                verbose_name="Attiva",
            ),
        ),
        migrations.AddField(
            model_name="chatbotentry",
            name="follow_ups",
            field=models.TextField(
                blank=True,
                help_text='Facoltative, una per riga (al massimo 3): compaiono come pulsanti sotto la risposta, e il chatbot risponde come se il visitatore le avesse scritte. Es. "Quanto costa?"',
                verbose_name="Domande successive proposte",
            ),
        ),
        migrations.AddField(
            model_name="chatbotentry",
            name="page",
            field=models.ForeignKey(
                blank=True,
                help_text='Facoltativa. Sotto la risposta compare "Scopri di più" verso questa pagina, e "Dimmi di più" continua con il testo della pagina.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Pagina collegata",
            ),
        ),
        migrations.AddField(
            model_name="chatbotquestion",
            name="answer_key",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="Chiave risposta"
            ),
        ),
        migrations.AddField(
            model_name="chatbotquestion",
            name="in_context",
            field=models.BooleanField(
                default=False,
                help_text="Sì = c'era già una domanda prima, il chatbot ne ha tenuto conto.",
                verbose_name="Durante una conversazione",
            ),
        ),
        migrations.AddField(
            model_name="chatbotquestion",
            name="kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("entry", "Voce chatbot"),
                    ("page", "Pagina del sito"),
                    ("passage", "Testo di una pagina"),
                    ("context", "Seguito della conversazione"),
                    ("more", "Dimmi di più"),
                    ("clarify", "Domanda di chiarimento"),
                    ("fallback", "Nessuna risposta"),
                    ("greeting", "Saluto"),
                    ("thanks", "Ringraziamento"),
                    ("unclear", "Domanda non chiara"),
                ],
                max_length=20,
                verbose_name="Come ha risposto",
            ),
        ),
    ]
