# Generated by Django 5.2.17 on 2026-10-03 10:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0007_alter_servicepage_body_alter_servicesindexpage_intro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 6),
                    ("rich_text", 7),
                    ("image", 11),
                    ("quote", 14),
                    ("cta", 19),
                    ("service_cards", 22),
                    ("columns", 24),
                    ("video_embed", 26),
                    ("download", 28),
                    ("spacer", 30),
                    ("stats", 36),
                    ("network_diagram", 37),
                    ("solution_cards", 44),
                    ("feature_grid", 48),
                    ("testimonial", 50),
                    ("partner_logos", 53),
                    ("portfolio_grid", 58),
                    ("text_section", 63),
                    ("product_feature", 70),
                    ("measures", 77),
                    ("steps", 83),
                    ("device_cards", 87),
                    ("case_cards", 91),
                    ("faq", 97),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 120,
                            "required": True,
                        },
                    ),
                    1: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    2: ("core.api_blocks.ImageChooserBlock", (), {"required": False}),
                    3: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 40,
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 200, "required": False},
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Predefinito"),
                                ("accent", "Accento"),
                                ("muted", "Attenuato"),
                            ],
                            "help_text": "Stile della sezione - usa i colori del tema attivo.",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 0),
                                ("subheading", 1),
                                ("background_image", 2),
                                ("cta_label", 3),
                                ("cta_url", 4),
                                ("variant", 5),
                            ]
                        ],
                        {},
                    ),
                    7: ("core.blocks.RichTextBlock", (), {}),
                    8: ("core.api_blocks.ImageChooserBlock", (), {"required": True}),
                    9: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 250,
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 250, "required": False},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 8), ("caption", 9), ("alt_text", 10)]],
                        {},
                    ),
                    12: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "required": True,
                        },
                    ),
                    13: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 120,
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 12), ("attribution", 13)]],
                        {},
                    ),
                    15: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "required": False,
                        },
                    ),
                    16: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "default": "Contattaci",
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 40,
                        },
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "/contatti/", "max_length": 200},
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("primary", "Primario"), ("subtle", "Discreto")]},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 0),
                                ("body", 15),
                                ("button_label", 16),
                                ("button_url", 17),
                                ("style", 18),
                            ]
                        ],
                        {},
                    ),
                    20: (
                        "core.api_blocks.PageChooserBlock",
                        (),
                        {"page_type": ["services.ServicePage"]},
                    ),
                    21: ("wagtail.blocks.ListBlock", (20,), {}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("services", 21)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 7), ("image", 11)]],
                        {"required": False},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("left", 23), ("right", 23)]],
                        {},
                    ),
                    25: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "URL YouTube o Vimeo", "required": True},
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("embed", 25), ("caption", 9)]],
                        {},
                    ),
                    27: (
                        "core.api_blocks.DocumentChooserBlock",
                        (),
                        {"required": True},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("document", 27), ("label", 13)]],
                        {},
                    ),
                    29: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Piccolo"),
                                ("md", "Medio"),
                                ("lg", "Grande"),
                            ]
                        },
                    ),
                    30: ("wagtail.blocks.StructBlock", [[("size", 29)]], {}),
                    31: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Numero puro, es. 500 (niente + o testo)"},
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "+", "max_length": 10, "required": False},
                    ),
                    33: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 80,
                        },
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("value", 31), ("suffix", 32), ("label", 33)]],
                        {},
                    ),
                    35: ("wagtail.blocks.ListBlock", (34,), {}),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("stats", 35), ("variant", 5)]],
                        {},
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("caption", 9)]],
                        {},
                    ),
                    38: (
                        "core.api_blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Icona SVG/PNG, es. smart-road.svg",
                            "required": False,
                        },
                    ),
                    39: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 60,
                        },
                    ),
                    40: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 200,
                        },
                    ),
                    41: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "default": "Scopri",
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 40,
                        },
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 38),
                                ("title", 39),
                                ("description", 40),
                                ("link_url", 4),
                                ("link_label", 41),
                            ]
                        ],
                        {},
                    ),
                    43: ("wagtail.blocks.ListBlock", (42,), {}),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("cards", 43)]],
                        {},
                    ),
                    45: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 160,
                            "required": False,
                        },
                    ),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 2), ("title", 39), ("description", 40)]],
                        {},
                    ),
                    47: ("wagtail.blocks.ListBlock", (46,), {}),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 45), ("subheading", 9), ("features", 47)]],
                        {},
                    ),
                    49: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    50: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("quote", 12),
                                ("name", 49),
                                ("role", 49),
                                ("avatar", 2),
                                ("variant", 5),
                            ]
                        ],
                        {},
                    ),
                    51: ("core.api_blocks.ImageChooserBlock", (), {}),
                    52: ("wagtail.blocks.ListBlock", (51,), {}),
                    53: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("logos", 52)]],
                        {},
                    ),
                    54: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "default": "Vedi tutto",
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 40,
                        },
                    ),
                    55: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 120,
                        },
                    ),
                    56: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 8),
                                ("title", 55),
                                ("client", 13),
                                ("excerpt", 1),
                                ("url", 4),
                            ]
                        ],
                        {},
                    ),
                    57: ("wagtail.blocks.ListBlock", (56,), {}),
                    58: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 13),
                                ("view_all_url", 4),
                                ("view_all_label", 54),
                                ("items", 57),
                            ]
                        ],
                        {},
                    ),
                    59: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Titolo", "max_length": 160},
                    ),
                    60: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "highlight",
                            ],
                            "label": "Testo",
                        },
                    ),
                    61: ("wagtail.blocks.CharBlock", (), {"max_length": 60}),
                    62: (
                        "wagtail.blocks.ListBlock",
                        (61,),
                        {
                            "help_text": "Brevi etichette mostrate come pillole sotto il testo, es. 'Eventi real-time'.",
                            "label": "Punti chiave",
                            "required": False,
                        },
                    ),
                    63: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 59), ("text", 60), ("highlights", 62)]],
                        {},
                    ),
                    64: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Es. 'La soluzione Axatel'",
                            "label": "Etichetta",
                            "max_length": 60,
                            "required": False,
                        },
                    ),
                    65: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Nome prodotto o servizio", "max_length": 120},
                    ),
                    66: ("wagtail.blocks.TextBlock", (), {"label": "Descrizione"}),
                    67: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Se scelta, il riquadro rimanda alla scheda del prodotto.",
                            "label": "Pagina prodotto",
                            "page_type": ["products.ProductPage"],
                            "required": False,
                        },
                    ),
                    68: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Es. una scheda tecnica PDF.",
                            "label": "Link alternativo",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    69: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Testo link", "max_length": 60, "required": False},
                    ),
                    70: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 64),
                                ("name", 65),
                                ("description", 66),
                                ("product", 67),
                                ("link_url", 68),
                                ("link_label", 69),
                            ]
                        ],
                        {},
                    ),
                    71: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Cosa misuriamo",
                            "label": "Titolo",
                            "max_length": 120,
                        },
                    ),
                    72: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Es. 'Inclinazione'",
                            "label": "Grandezza",
                            "max_length": 80,
                        },
                    ),
                    73: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Es. 'mrad', 'µg/m³', 'veic/h'",
                            "label": "Unità",
                            "max_length": 30,
                            "required": False,
                        },
                    ),
                    74: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Nota", "max_length": 160, "required": False},
                    ),
                    75: (
                        "wagtail.blocks.StructBlock",
                        [[("quantity", 72), ("unit", 73), ("note", 74)]],
                        {},
                    ),
                    76: ("wagtail.blocks.ListBlock", (75,), {"label": "Grandezze"}),
                    77: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 71), ("items", 76)]],
                        {},
                    ),
                    78: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Come funziona",
                            "label": "Titolo",
                            "max_length": 120,
                        },
                    ),
                    79: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Titolo", "max_length": 80},
                    ),
                    80: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Testo", "required": False},
                    ),
                    81: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 79), ("text", 80)]],
                        {},
                    ),
                    82: ("wagtail.blocks.ListBlock", (81,), {"label": "Passaggi"}),
                    83: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 78), ("steps", 82)]],
                        {},
                    ),
                    84: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Dispositivi utilizzati",
                            "label": "Titolo",
                            "max_length": 120,
                        },
                    ),
                    85: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["products.ProductPage"]},
                    ),
                    86: ("wagtail.blocks.ListBlock", (85,), {"label": "Prodotti"}),
                    87: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 84), ("products", 86)]],
                        {},
                    ),
                    88: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Casi di successo",
                            "label": "Titolo",
                            "max_length": 120,
                        },
                    ),
                    89: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["casi.CasoSuccessoPage"]},
                    ),
                    90: ("wagtail.blocks.ListBlock", (89,), {"label": "Casi"}),
                    91: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 88), ("cases", 90)]],
                        {},
                    ),
                    92: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Domande frequenti",
                            "label": "Titolo",
                            "max_length": 120,
                            "required": False,
                        },
                    ),
                    93: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Domanda", "max_length": 200},
                    ),
                    94: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "ol", "ul"],
                            "label": "Risposta",
                        },
                    ),
                    95: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 93), ("answer", 94)]],
                        {},
                    ),
                    96: ("wagtail.blocks.ListBlock", (95,), {"label": "Domande"}),
                    97: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 92), ("items", 96)]],
                        {},
                    ),
                },
                verbose_name="Contenuto dettaglio servizio",
            ),
        ),
        migrations.AlterField(
            model_name="servicesindexpage",
            name="intro",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 6),
                    ("rich_text", 7),
                    ("image", 11),
                    ("quote", 14),
                    ("cta", 19),
                    ("service_cards", 22),
                    ("columns", 24),
                    ("video_embed", 26),
                    ("download", 28),
                    ("spacer", 30),
                    ("stats", 36),
                    ("network_diagram", 37),
                    ("solution_cards", 44),
                    ("feature_grid", 48),
                    ("testimonial", 50),
                    ("partner_logos", 53),
                    ("portfolio_grid", 58),
                    ("text_section", 63),
                    ("product_feature", 70),
                    ("measures", 77),
                    ("steps", 83),
                    ("device_cards", 87),
                    ("case_cards", 91),
                    ("faq", 97),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 120,
                            "required": True,
                        },
                    ),
                    1: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    2: ("core.api_blocks.ImageChooserBlock", (), {"required": False}),
                    3: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 40,
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 200, "required": False},
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Predefinito"),
                                ("accent", "Accento"),
                                ("muted", "Attenuato"),
                            ],
                            "help_text": "Stile della sezione - usa i colori del tema attivo.",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 0),
                                ("subheading", 1),
                                ("background_image", 2),
                                ("cta_label", 3),
                                ("cta_url", 4),
                                ("variant", 5),
                            ]
                        ],
                        {},
                    ),
                    7: ("core.blocks.RichTextBlock", (), {}),
                    8: ("core.api_blocks.ImageChooserBlock", (), {"required": True}),
                    9: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 250,
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 250, "required": False},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 8), ("caption", 9), ("alt_text", 10)]],
                        {},
                    ),
                    12: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "required": True,
                        },
                    ),
                    13: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 120,
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 12), ("attribution", 13)]],
                        {},
                    ),
                    15: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "required": False,
                        },
                    ),
                    16: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "default": "Contattaci",
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 40,
                        },
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "/contatti/", "max_length": 200},
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("primary", "Primario"), ("subtle", "Discreto")]},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 0),
                                ("body", 15),
                                ("button_label", 16),
                                ("button_url", 17),
                                ("style", 18),
                            ]
                        ],
                        {},
                    ),
                    20: (
                        "core.api_blocks.PageChooserBlock",
                        (),
                        {"page_type": ["services.ServicePage"]},
                    ),
                    21: ("wagtail.blocks.ListBlock", (20,), {}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("services", 21)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 7), ("image", 11)]],
                        {"required": False},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("left", 23), ("right", 23)]],
                        {},
                    ),
                    25: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "URL YouTube o Vimeo", "required": True},
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("embed", 25), ("caption", 9)]],
                        {},
                    ),
                    27: (
                        "core.api_blocks.DocumentChooserBlock",
                        (),
                        {"required": True},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("document", 27), ("label", 13)]],
                        {},
                    ),
                    29: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Piccolo"),
                                ("md", "Medio"),
                                ("lg", "Grande"),
                            ]
                        },
                    ),
                    30: ("wagtail.blocks.StructBlock", [[("size", 29)]], {}),
                    31: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Numero puro, es. 500 (niente + o testo)"},
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "+", "max_length": 10, "required": False},
                    ),
                    33: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 80,
                        },
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("value", 31), ("suffix", 32), ("label", 33)]],
                        {},
                    ),
                    35: ("wagtail.blocks.ListBlock", (34,), {}),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("stats", 35), ("variant", 5)]],
                        {},
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("caption", 9)]],
                        {},
                    ),
                    38: (
                        "core.api_blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Icona SVG/PNG, es. smart-road.svg",
                            "required": False,
                        },
                    ),
                    39: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 60,
                        },
                    ),
                    40: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 200,
                        },
                    ),
                    41: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "default": "Scopri",
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 40,
                        },
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 38),
                                ("title", 39),
                                ("description", 40),
                                ("link_url", 4),
                                ("link_label", 41),
                            ]
                        ],
                        {},
                    ),
                    43: ("wagtail.blocks.ListBlock", (42,), {}),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("cards", 43)]],
                        {},
                    ),
                    45: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 160,
                            "required": False,
                        },
                    ),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 2), ("title", 39), ("description", 40)]],
                        {},
                    ),
                    47: ("wagtail.blocks.ListBlock", (46,), {}),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 45), ("subheading", 9), ("features", 47)]],
                        {},
                    ),
                    49: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    50: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("quote", 12),
                                ("name", 49),
                                ("role", 49),
                                ("avatar", 2),
                                ("variant", 5),
                            ]
                        ],
                        {},
                    ),
                    51: ("core.api_blocks.ImageChooserBlock", (), {}),
                    52: ("wagtail.blocks.ListBlock", (51,), {}),
                    53: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("logos", 52)]],
                        {},
                    ),
                    54: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "default": "Vedi tutto",
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 40,
                        },
                    ),
                    55: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 120,
                        },
                    ),
                    56: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 8),
                                ("title", 55),
                                ("client", 13),
                                ("excerpt", 1),
                                ("url", 4),
                            ]
                        ],
                        {},
                    ),
                    57: ("wagtail.blocks.ListBlock", (56,), {}),
                    58: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 13),
                                ("view_all_url", 4),
                                ("view_all_label", 54),
                                ("items", 57),
                            ]
                        ],
                        {},
                    ),
                    59: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Titolo", "max_length": 160},
                    ),
                    60: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "highlight",
                            ],
                            "label": "Testo",
                        },
                    ),
                    61: ("wagtail.blocks.CharBlock", (), {"max_length": 60}),
                    62: (
                        "wagtail.blocks.ListBlock",
                        (61,),
                        {
                            "help_text": "Brevi etichette mostrate come pillole sotto il testo, es. 'Eventi real-time'.",
                            "label": "Punti chiave",
                            "required": False,
                        },
                    ),
                    63: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 59), ("text", 60), ("highlights", 62)]],
                        {},
                    ),
                    64: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Es. 'La soluzione Axatel'",
                            "label": "Etichetta",
                            "max_length": 60,
                            "required": False,
                        },
                    ),
                    65: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Nome prodotto o servizio", "max_length": 120},
                    ),
                    66: ("wagtail.blocks.TextBlock", (), {"label": "Descrizione"}),
                    67: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Se scelta, il riquadro rimanda alla scheda del prodotto.",
                            "label": "Pagina prodotto",
                            "page_type": ["products.ProductPage"],
                            "required": False,
                        },
                    ),
                    68: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Es. una scheda tecnica PDF.",
                            "label": "Link alternativo",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    69: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Testo link", "max_length": 60, "required": False},
                    ),
                    70: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 64),
                                ("name", 65),
                                ("description", 66),
                                ("product", 67),
                                ("link_url", 68),
                                ("link_label", 69),
                            ]
                        ],
                        {},
                    ),
                    71: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Cosa misuriamo",
                            "label": "Titolo",
                            "max_length": 120,
                        },
                    ),
                    72: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Es. 'Inclinazione'",
                            "label": "Grandezza",
                            "max_length": 80,
                        },
                    ),
                    73: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Es. 'mrad', 'µg/m³', 'veic/h'",
                            "label": "Unità",
                            "max_length": 30,
                            "required": False,
                        },
                    ),
                    74: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Nota", "max_length": 160, "required": False},
                    ),
                    75: (
                        "wagtail.blocks.StructBlock",
                        [[("quantity", 72), ("unit", 73), ("note", 74)]],
                        {},
                    ),
                    76: ("wagtail.blocks.ListBlock", (75,), {"label": "Grandezze"}),
                    77: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 71), ("items", 76)]],
                        {},
                    ),
                    78: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Come funziona",
                            "label": "Titolo",
                            "max_length": 120,
                        },
                    ),
                    79: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Titolo", "max_length": 80},
                    ),
                    80: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Testo", "required": False},
                    ),
                    81: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 79), ("text", 80)]],
                        {},
                    ),
                    82: ("wagtail.blocks.ListBlock", (81,), {"label": "Passaggi"}),
                    83: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 78), ("steps", 82)]],
                        {},
                    ),
                    84: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Dispositivi utilizzati",
                            "label": "Titolo",
                            "max_length": 120,
                        },
                    ),
                    85: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["products.ProductPage"]},
                    ),
                    86: ("wagtail.blocks.ListBlock", (85,), {"label": "Prodotti"}),
                    87: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 84), ("products", 86)]],
                        {},
                    ),
                    88: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Casi di successo",
                            "label": "Titolo",
                            "max_length": 120,
                        },
                    ),
                    89: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["casi.CasoSuccessoPage"]},
                    ),
                    90: ("wagtail.blocks.ListBlock", (89,), {"label": "Casi"}),
                    91: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 88), ("cases", 90)]],
                        {},
                    ),
                    92: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Domande frequenti",
                            "label": "Titolo",
                            "max_length": 120,
                            "required": False,
                        },
                    ),
                    93: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Domanda", "max_length": 200},
                    ),
                    94: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "ol", "ul"],
                            "label": "Risposta",
                        },
                    ),
                    95: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 93), ("answer", 94)]],
                        {},
                    ),
                    96: ("wagtail.blocks.ListBlock", (95,), {"label": "Domande"}),
                    97: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 92), ("items", 96)]],
                        {},
                    ),
                },
                verbose_name="Introduzione (sopra le card servizi)",
            ),
        ),
    ]
