# Generated by Django 5.2.16 on 2026-07-29 20:38

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasiIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('canonical_url', models.URLField(blank=True, help_text="Leave blank to use the page's URL.", max_length=255, verbose_name='Canonical URL')),
                ('intro', models.TextField(blank=True, help_text="Testo mostrato sopra l'elenco dei casi.", verbose_name='Introduzione')),
                ('og_image', models.ForeignKey(blank=True, help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Preview image')),
            ],
            options={
                'verbose_name': 'Indice Casi di successo',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='CasoSuccessoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('canonical_url', models.URLField(blank=True, help_text="Leave blank to use the page's URL.", max_length=255, verbose_name='Canonical URL')),
                ('client', models.CharField(blank=True, help_text="Es. 'Provincia di Belluno · ANAS'", max_length=150, verbose_name='Cliente')),
                ('category', models.CharField(blank=True, help_text="Es. 'Smart Road', 'Gallerie', 'Corporate'", max_length=100, verbose_name='Categoria')),
                ('description', models.TextField(blank=True, help_text='Testo mostrato nella card del carosello. Usato anche come meta description se il tab Promuovi è vuoto.', max_length=300, verbose_name='Descrizione (card)')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='Contenuto')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Immagine di copertina')),
                ('og_image', models.ForeignKey(blank=True, help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Preview image')),
            ],
            options={
                'verbose_name': 'Caso di successo',
                'verbose_name_plural': 'Casi di successo',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='CasoSuccessoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='casi.casosuccessopage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='casosuccessopage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='casi.CasoSuccessoTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
