# Generated by Django 5.2.17 on 2026-10-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("casi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="casosuccessopage",
            name="event_date",
            field=models.DateField(
                blank=True,
                help_text="Quando si è svolto il progetto o l'evento (basta anche il 1° del mese). Nell'elenco e in homepage i casi più recenti compaiono per primi; quelli senza data vengono dopo, nell'ordine di pubblicazione.",
                null=True,
                verbose_name="Data del progetto",
            ),
        ),
    ]
