# Generated by Django 5.2.17 on 2026-10-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casi', '0002_casosuccessopage_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='casosuccessopage',
            name='client_label',
            field=models.CharField(blank=True, default='Cliente', help_text="Testo mostrato prima del cliente (es. 'Cliente', 'Committente'). Lascia vuoto per mostrare solo il nome del cliente, senza etichetta.", max_length=50, verbose_name='Etichetta cliente'),
        ),
        migrations.AddField(
            model_name='casosuccessopage',
            name='show_card_title',
            field=models.BooleanField(default=False, help_text="Attiva se l'immagine di copertina non contiene già il titolo.", verbose_name='Mostra titolo nella card'),
        ),
        migrations.AlterField(
            model_name='casosuccessopage',
            name='description',
            field=models.TextField(blank=True, help_text='Testo mostrato nella card del carosello. Se vuoto, viene generato automaticamente un estratto del contenuto. Usato anche come meta description se il tab Promuovi è vuoto.', max_length=300, verbose_name='Descrizione (card)'),
        ),
    ]
