# Generated by Django 5.2.16 on 2026-07-19 11:58

import django.db.models.deletion
import django.utils.timezone
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('canonical_url', models.URLField(blank=True, help_text="Leave blank to use the page's URL.", max_length=255, verbose_name='Canonical URL')),
                ('intro', wagtail.fields.StreamField([('hero', 4), ('rich_text', 5), ('image', 9), ('quote', 12), ('cta', 17), ('service_cards', 20), ('columns', 22), ('video_embed', 24), ('download', 26), ('spacer', 28)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subheading', 1), ('background_image', 2), ('cta_label', 3), ('cta_url', 1)]], {}), 5: ('core.blocks.RichTextBlock', (), {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': "Override alt text; falls back to the image's own alt text.", 'max_length': 250, 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('image', 6), ('caption', 7), ('alt_text', 8)]], {}), 10: ('wagtail.blocks.TextBlock', (), {'required': True}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('quote', 10), ('attribution', 11)]], {}), 13: ('wagtail.blocks.TextBlock', (), {'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'default': 'Contattaci', 'max_length': 40}), 15: ('wagtail.blocks.CharBlock', (), {'default': '/contatti/', 'max_length': 200}), 16: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primario'), ('subtle', 'Discreto')]}), 17: ('wagtail.blocks.StructBlock', [[('heading', 0), ('body', 13), ('button_label', 14), ('button_url', 15), ('style', 16)]], {}), 18: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['services.ServicePage']}), 19: ('wagtail.blocks.ListBlock', (18,), {}), 20: ('wagtail.blocks.StructBlock', [[('heading', 11), ('services', 19)]], {}), 21: ('wagtail.blocks.StreamBlock', [[('rich_text', 5), ('image', 9)]], {'required': False}), 22: ('wagtail.blocks.StructBlock', [[('left', 21), ('right', 21)]], {}), 23: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'URL YouTube o Vimeo', 'required': True}), 24: ('wagtail.blocks.StructBlock', [[('embed', 23), ('caption', 7)]], {}), 25: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True}), 26: ('wagtail.blocks.StructBlock', [[('document', 25), ('label', 11)]], {}), 27: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('sm', 'Piccolo'), ('md', 'Medio'), ('lg', 'Grande')]}), 28: ('wagtail.blocks.StructBlock', [[('size', 27)]], {})}, verbose_name='Introduzione blog')),
                ('og_image', models.ForeignKey(blank=True, help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Preview image')),
            ],
            options={
                'verbose_name': 'Indice Blog',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('canonical_url', models.URLField(blank=True, help_text="Leave blank to use the page's URL.", max_length=255, verbose_name='Canonical URL')),
                ('author', models.CharField(blank=True, default='Axatel Team', max_length=100, verbose_name='Autore')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Data pubblicazione')),
                ('intro', models.TextField(blank=True, help_text='Estratto mostrato nelle card e usato come meta description.', max_length=400, verbose_name='Estratto')),
                ('body', wagtail.fields.StreamField([('hero', 4), ('rich_text', 5), ('image', 9), ('quote', 12), ('cta', 17), ('service_cards', 20), ('columns', 22), ('video_embed', 24), ('download', 26), ('spacer', 28)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subheading', 1), ('background_image', 2), ('cta_label', 3), ('cta_url', 1)]], {}), 5: ('core.blocks.RichTextBlock', (), {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': "Override alt text; falls back to the image's own alt text.", 'max_length': 250, 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('image', 6), ('caption', 7), ('alt_text', 8)]], {}), 10: ('wagtail.blocks.TextBlock', (), {'required': True}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('quote', 10), ('attribution', 11)]], {}), 13: ('wagtail.blocks.TextBlock', (), {'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'default': 'Contattaci', 'max_length': 40}), 15: ('wagtail.blocks.CharBlock', (), {'default': '/contatti/', 'max_length': 200}), 16: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primario'), ('subtle', 'Discreto')]}), 17: ('wagtail.blocks.StructBlock', [[('heading', 0), ('body', 13), ('button_label', 14), ('button_url', 15), ('style', 16)]], {}), 18: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['services.ServicePage']}), 19: ('wagtail.blocks.ListBlock', (18,), {}), 20: ('wagtail.blocks.StructBlock', [[('heading', 11), ('services', 19)]], {}), 21: ('wagtail.blocks.StreamBlock', [[('rich_text', 5), ('image', 9)]], {'required': False}), 22: ('wagtail.blocks.StructBlock', [[('left', 21), ('right', 21)]], {}), 23: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'URL YouTube o Vimeo', 'required': True}), 24: ('wagtail.blocks.StructBlock', [[('embed', 23), ('caption', 7)]], {}), 25: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True}), 26: ('wagtail.blocks.StructBlock', [[('document', 25), ('label', 11)]], {}), 27: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('sm', 'Piccolo'), ('md', 'Medio'), ('lg', 'Grande')]}), 28: ('wagtail.blocks.StructBlock', [[('size', 27)]], {})}, verbose_name='Corpo articolo')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Immagine di copertina')),
                ('og_image', models.ForeignKey(blank=True, help_text='Shown when linking to this page on social media. If blank, may show an image from the page, or the default from Settings > SEO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Preview image')),
            ],
            options={
                'verbose_name': 'Articolo Blog',
                'verbose_name_plural': 'Articoli Blog',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='BlogPostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='blog.blogpost')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blog.BlogPostTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
