# Generated by Django 5.2.17 on 2026-10-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_blogindexpage_intro_alter_blogpost_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogindexpage",
            options={"verbose_name": "Indice News"},
        ),
        migrations.AlterModelOptions(
            name="blogpost",
            options={
                "verbose_name": "Articolo News",
                "verbose_name_plural": "Articoli Blog",
            },
        ),
    ]
