# Generated by Django 5.2.17 on 2026-10-03 20:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_no_service_cards"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogindexpage",
            name="intro",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 6),
                    ("rich_text", 7),
                    ("image", 11),
                    ("quote", 14),
                    ("cta", 19),
                    ("columns", 21),
                    ("video_embed", 23),
                    ("download", 25),
                    ("spacer", 27),
                    ("stats", 33),
                    ("network_diagram", 34),
                    ("solution_cards", 41),
                    ("feature_grid", 45),
                    ("testimonial", 47),
                    ("partner_logos", 50),
                    ("portfolio_grid", 55),
                    ("text_section", 60),
                    ("product_feature", 74),
                    ("measures", 81),
                    ("steps", 87),
                    ("device_cards", 91),
                    ("case_cards", 95),
                    ("faq", 101),
                    ("contact_form", 111),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 120,
                            "required": True,
                        },
                    ),
                    1: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    2: ("core.api_blocks.ImageChooserBlock", (), {"required": False}),
                    3: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 40,
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 200, "required": False},
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Predefinito"),
                                ("accent", "Accento"),
                                ("muted", "Attenuato"),
                            ],
                            "help_text": "Stile della sezione - usa i colori del tema attivo.",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 0),
                                ("subheading", 1),
                                ("background_image", 2),
                                ("cta_label", 3),
                                ("cta_url", 4),
                                ("variant", 5),
                            ]
                        ],
                        {},
                    ),
                    7: ("core.blocks.RichTextBlock", (), {}),
                    8: ("core.api_blocks.ImageChooserBlock", (), {"required": True}),
                    9: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 250,
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 250, "required": False},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 8), ("caption", 9), ("alt_text", 10)]],
                        {},
                    ),
                    12: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "required": True,
                        },
                    ),
                    13: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 120,
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 12), ("attribution", 13)]],
                        {},
                    ),
                    15: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "required": False,
                        },
                    ),
                    16: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "default": "Contattaci",
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 40,
                        },
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "/contatti/", "max_length": 200},
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("primary", "Primario"), ("subtle", "Discreto")]},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 0),
                                ("body", 15),
                                ("button_label", 16),
                                ("button_url", 17),
                                ("style", 18),
                            ]
                        ],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 7), ("image", 11)]],
                        {"required": False},
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("left", 20), ("right", 20)]],
                        {},
                    ),
                    22: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "URL YouTube o Vimeo", "required": True},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("embed", 22), ("caption", 9)]],
                        {},
                    ),
                    24: (
                        "core.api_blocks.DocumentChooserBlock",
                        (),
                        {"required": True},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("document", 24), ("label", 13)]],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Piccolo"),
                                ("md", "Medio"),
                                ("lg", "Grande"),
                            ]
                        },
                    ),
                    27: ("wagtail.blocks.StructBlock", [[("size", 26)]], {}),
                    28: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Numero puro, es. 500 (niente + o testo)"},
                    ),
                    29: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "+", "max_length": 10, "required": False},
                    ),
                    30: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 80,
                        },
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("value", 28), ("suffix", 29), ("label", 30)]],
                        {},
                    ),
                    32: ("wagtail.blocks.ListBlock", (31,), {}),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("stats", 32), ("variant", 5)]],
                        {},
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("caption", 9)]],
                        {},
                    ),
                    35: (
                        "core.api_blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Icona SVG/PNG, es. smart-road.svg",
                            "required": False,
                        },
                    ),
                    36: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 60,
                        },
                    ),
                    37: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 200,
                        },
                    ),
                    38: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "default": "Scopri",
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 40,
                        },
                    ),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 35),
                                ("title", 36),
                                ("description", 37),
                                ("link_url", 4),
                                ("link_label", 38),
                            ]
                        ],
                        {},
                    ),
                    40: ("wagtail.blocks.ListBlock", (39,), {}),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("cards", 40)]],
                        {},
                    ),
                    42: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 160,
                            "required": False,
                        },
                    ),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 2), ("title", 36), ("description", 37)]],
                        {},
                    ),
                    44: ("wagtail.blocks.ListBlock", (43,), {}),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 42), ("subheading", 9), ("features", 44)]],
                        {},
                    ),
                    46: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("quote", 12),
                                ("name", 46),
                                ("role", 46),
                                ("avatar", 2),
                                ("variant", 5),
                            ]
                        ],
                        {},
                    ),
                    48: ("core.api_blocks.ImageChooserBlock", (), {}),
                    49: ("wagtail.blocks.ListBlock", (48,), {}),
                    50: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("logos", 49)]],
                        {},
                    ),
                    51: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "default": "Vedi tutto",
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 40,
                        },
                    ),
                    52: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 120,
                        },
                    ),
                    53: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 8),
                                ("title", 52),
                                ("client", 13),
                                ("excerpt", 1),
                                ("url", 4),
                            ]
                        ],
                        {},
                    ),
                    54: ("wagtail.blocks.ListBlock", (53,), {}),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 13),
                                ("view_all_url", 4),
                                ("view_all_label", 51),
                                ("items", 54),
                            ]
                        ],
                        {},
                    ),
                    56: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Titolo", "max_length": 160},
                    ),
                    57: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "highlight",
                            ],
                            "label": "Testo",
                        },
                    ),
                    58: ("wagtail.blocks.CharBlock", (), {"max_length": 60}),
                    59: (
                        "wagtail.blocks.ListBlock",
                        (58,),
                        {
                            "help_text": "Brevi etichette mostrate come pillole sotto il testo, es. 'Eventi real-time'.",
                            "label": "Punti chiave",
                            "required": False,
                        },
                    ),
                    60: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 56), ("text", 57), ("highlights", 59)]],
                        {},
                    ),
                    61: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Es. 'La soluzione Axatel'",
                            "label": "Etichetta",
                            "max_length": 60,
                            "required": False,
                        },
                    ),
                    62: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Nome prodotto o servizio", "max_length": 120},
                    ),
                    63: ("wagtail.blocks.TextBlock", (), {"label": "Descrizione"}),
                    64: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Se scelta, il primo pulsante (rosso) rimanda alla scheda del prodotto.",
                            "label": "Pagina prodotto",
                            "page_type": ["products.ProductPage"],
                            "required": False,
                        },
                    ),
                    65: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Vecchio campo per un solo link: per i PDF usa i Pulsanti qui sotto.",
                            "label": "Link alternativo",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    66: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Testo link", "max_length": 60, "required": False},
                    ),
                    67: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Es. 'Scheda tecnica', 'Manuale', 'Video'",
                            "label": "Testo del pulsante",
                            "max_length": 60,
                        },
                    ),
                    68: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Pagina del sito", "required": False},
                    ),
                    69: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Carica il file in Documenti: resta sul vostro server e si apre in una nuova scheda.",
                            "label": "Documento (PDF)",
                            "required": False,
                        },
                    ),
                    70: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Es. https://… o /contatti",
                            "label": "Oppure un indirizzo",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    71: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("secondary", "Contorno"),
                                ("primary", "Pieno (rosso)"),
                            ],
                            "label": "Aspetto",
                        },
                    ),
                    72: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 67),
                                ("page", 68),
                                ("document", 69),
                                ("url", 70),
                                ("style", 71),
                            ]
                        ],
                        {},
                    ),
                    73: (
                        "wagtail.blocks.ListBlock",
                        (72,),
                        {
                            "help_text": "Quanti ne servono: schede tecniche, manuali, pagine collegate. Trascina per cambiare l'ordine.",
                            "label": "Pulsanti",
                            "required": False,
                        },
                    ),
                    74: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 61),
                                ("name", 62),
                                ("description", 63),
                                ("product", 64),
                                ("link_url", 65),
                                ("link_label", 66),
                                ("buttons", 73),
                            ]
                        ],
                        {},
                    ),
                    75: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Cosa misuriamo",
                            "label": "Titolo",
                            "max_length": 120,
                        },
                    ),
                    76: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Es. 'Inclinazione'",
                            "label": "Grandezza",
                            "max_length": 80,
                        },
                    ),
                    77: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Es. 'mrad', 'µg/m³', 'veic/h'",
                            "label": "Unità",
                            "max_length": 30,
                            "required": False,
                        },
                    ),
                    78: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Nota", "max_length": 160, "required": False},
                    ),
                    79: (
                        "wagtail.blocks.StructBlock",
                        [[("quantity", 76), ("unit", 77), ("note", 78)]],
                        {},
                    ),
                    80: ("wagtail.blocks.ListBlock", (79,), {"label": "Grandezze"}),
                    81: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 75), ("items", 80)]],
                        {},
                    ),
                    82: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Come funziona",
                            "label": "Titolo",
                            "max_length": 120,
                        },
                    ),
                    83: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Titolo", "max_length": 80},
                    ),
                    84: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Testo", "required": False},
                    ),
                    85: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 83), ("text", 84)]],
                        {},
                    ),
                    86: ("wagtail.blocks.ListBlock", (85,), {"label": "Passaggi"}),
                    87: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 82), ("steps", 86)]],
                        {},
                    ),
                    88: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Dispositivi utilizzati",
                            "label": "Titolo",
                            "max_length": 120,
                        },
                    ),
                    89: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["products.ProductPage"]},
                    ),
                    90: ("wagtail.blocks.ListBlock", (89,), {"label": "Prodotti"}),
                    91: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 88), ("products", 90)]],
                        {},
                    ),
                    92: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Casi di successo",
                            "label": "Titolo",
                            "max_length": 120,
                        },
                    ),
                    93: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["casi.CasoSuccessoPage"]},
                    ),
                    94: ("wagtail.blocks.ListBlock", (93,), {"label": "Casi"}),
                    95: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 92), ("cases", 94)]],
                        {},
                    ),
                    96: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Domande frequenti",
                            "label": "Titolo",
                            "max_length": 120,
                            "required": False,
                        },
                    ),
                    97: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Domanda", "max_length": 200},
                    ),
                    98: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "ol", "ul"],
                            "label": "Risposta",
                        },
                    ),
                    99: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 97), ("answer", 98)]],
                        {},
                    ),
                    100: ("wagtail.blocks.ListBlock", (99,), {"label": "Domande"}),
                    101: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 96), ("items", 100)]],
                        {},
                    ),
                    102: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Scrivici",
                            "label": "Titolo",
                            "max_length": 120,
                            "required": False,
                        },
                    ),
                    103: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Testo sopra il modulo", "required": False},
                    ),
                    104: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("contact", "Richiesta di contatto"),
                                (
                                    "partner",
                                    "Proposta di collaborazione (Diventa partner)",
                                ),
                                ("candidate", "Candidatura (Lavora con noi)"),
                                ("quote", "Richiesta di preventivo"),
                            ],
                            "help_text": "Così sai da quale pagina arriva la richiesta.",
                            "label": "Tipo di richiesta",
                        },
                    ),
                    105: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "label": "Chiedi l'azienda",
                            "required": False,
                        },
                    ),
                    106: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "label": "Chiedi il telefono",
                            "required": False,
                        },
                    ),
                    107: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "label": "Chiedi un messaggio",
                            "required": False,
                        },
                    ),
                    108: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "PDF, Word, ODT, RTF o TXT, massimo 10 MB.",
                            "label": "Permetti un allegato (CV o documento)",
                            "required": False,
                        },
                    ),
                    109: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Vuoto = 'Invia richiesta'.",
                            "label": "Testo del pulsante",
                            "max_length": 40,
                            "required": False,
                        },
                    ),
                    110: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Vuoto = 'Richiesta inviata. Ti risponderemo al più presto.'",
                            "label": "Messaggio dopo l'invio",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    111: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 102),
                                ("intro", 103),
                                ("form_type", 104),
                                ("show_company", 105),
                                ("show_phone", 106),
                                ("show_message", 107),
                                ("show_attachment", 108),
                                ("submit_label", 109),
                                ("success_message", 110),
                            ]
                        ],
                        {},
                    ),
                },
                verbose_name="Introduzione blog",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 6),
                    ("rich_text", 7),
                    ("image", 11),
                    ("quote", 14),
                    ("cta", 19),
                    ("columns", 21),
                    ("video_embed", 23),
                    ("download", 25),
                    ("spacer", 27),
                    ("stats", 33),
                    ("network_diagram", 34),
                    ("solution_cards", 41),
                    ("feature_grid", 45),
                    ("testimonial", 47),
                    ("partner_logos", 50),
                    ("portfolio_grid", 55),
                    ("text_section", 60),
                    ("product_feature", 74),
                    ("measures", 81),
                    ("steps", 87),
                    ("device_cards", 91),
                    ("case_cards", 95),
                    ("faq", 101),
                    ("contact_form", 111),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 120,
                            "required": True,
                        },
                    ),
                    1: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    2: ("core.api_blocks.ImageChooserBlock", (), {"required": False}),
                    3: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 40,
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 200, "required": False},
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Predefinito"),
                                ("accent", "Accento"),
                                ("muted", "Attenuato"),
                            ],
                            "help_text": "Stile della sezione - usa i colori del tema attivo.",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 0),
                                ("subheading", 1),
                                ("background_image", 2),
                                ("cta_label", 3),
                                ("cta_url", 4),
                                ("variant", 5),
                            ]
                        ],
                        {},
                    ),
                    7: ("core.blocks.RichTextBlock", (), {}),
                    8: ("core.api_blocks.ImageChooserBlock", (), {"required": True}),
                    9: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 250,
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 250, "required": False},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 8), ("caption", 9), ("alt_text", 10)]],
                        {},
                    ),
                    12: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "required": True,
                        },
                    ),
                    13: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 120,
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 12), ("attribution", 13)]],
                        {},
                    ),
                    15: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "required": False,
                        },
                    ),
                    16: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "default": "Contattaci",
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 40,
                        },
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "/contatti/", "max_length": 200},
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("primary", "Primario"), ("subtle", "Discreto")]},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 0),
                                ("body", 15),
                                ("button_label", 16),
                                ("button_url", 17),
                                ("style", 18),
                            ]
                        ],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 7), ("image", 11)]],
                        {"required": False},
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("left", 20), ("right", 20)]],
                        {},
                    ),
                    22: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "URL YouTube o Vimeo", "required": True},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("embed", 22), ("caption", 9)]],
                        {},
                    ),
                    24: (
                        "core.api_blocks.DocumentChooserBlock",
                        (),
                        {"required": True},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("document", 24), ("label", 13)]],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Piccolo"),
                                ("md", "Medio"),
                                ("lg", "Grande"),
                            ]
                        },
                    ),
                    27: ("wagtail.blocks.StructBlock", [[("size", 26)]], {}),
                    28: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Numero puro, es. 500 (niente + o testo)"},
                    ),
                    29: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "+", "max_length": 10, "required": False},
                    ),
                    30: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 80,
                        },
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("value", 28), ("suffix", 29), ("label", 30)]],
                        {},
                    ),
                    32: ("wagtail.blocks.ListBlock", (31,), {}),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("stats", 32), ("variant", 5)]],
                        {},
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("caption", 9)]],
                        {},
                    ),
                    35: (
                        "core.api_blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Icona SVG/PNG, es. smart-road.svg",
                            "required": False,
                        },
                    ),
                    36: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 60,
                        },
                    ),
                    37: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 200,
                        },
                    ),
                    38: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "default": "Scopri",
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 40,
                        },
                    ),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 35),
                                ("title", 36),
                                ("description", 37),
                                ("link_url", 4),
                                ("link_label", 38),
                            ]
                        ],
                        {},
                    ),
                    40: ("wagtail.blocks.ListBlock", (39,), {}),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("cards", 40)]],
                        {},
                    ),
                    42: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 160,
                            "required": False,
                        },
                    ),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 2), ("title", 36), ("description", 37)]],
                        {},
                    ),
                    44: ("wagtail.blocks.ListBlock", (43,), {}),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 42), ("subheading", 9), ("features", 44)]],
                        {},
                    ),
                    46: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("quote", 12),
                                ("name", 46),
                                ("role", 46),
                                ("avatar", 2),
                                ("variant", 5),
                            ]
                        ],
                        {},
                    ),
                    48: ("core.api_blocks.ImageChooserBlock", (), {}),
                    49: ("wagtail.blocks.ListBlock", (48,), {}),
                    50: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("logos", 49)]],
                        {},
                    ),
                    51: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "default": "Vedi tutto",
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 40,
                        },
                    ),
                    52: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "highlight", "link"],
                            "max_length": 120,
                        },
                    ),
                    53: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 8),
                                ("title", 52),
                                ("client", 13),
                                ("excerpt", 1),
                                ("url", 4),
                            ]
                        ],
                        {},
                    ),
                    54: ("wagtail.blocks.ListBlock", (53,), {}),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 13),
                                ("view_all_url", 4),
                                ("view_all_label", 51),
                                ("items", 54),
                            ]
                        ],
                        {},
                    ),
                    56: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Titolo", "max_length": 160},
                    ),
                    57: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "highlight",
                            ],
                            "label": "Testo",
                        },
                    ),
                    58: ("wagtail.blocks.CharBlock", (), {"max_length": 60}),
                    59: (
                        "wagtail.blocks.ListBlock",
                        (58,),
                        {
                            "help_text": "Brevi etichette mostrate come pillole sotto il testo, es. 'Eventi real-time'.",
                            "label": "Punti chiave",
                            "required": False,
                        },
                    ),
                    60: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 56), ("text", 57), ("highlights", 59)]],
                        {},
                    ),
                    61: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Es. 'La soluzione Axatel'",
                            "label": "Etichetta",
                            "max_length": 60,
                            "required": False,
                        },
                    ),
                    62: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Nome prodotto o servizio", "max_length": 120},
                    ),
                    63: ("wagtail.blocks.TextBlock", (), {"label": "Descrizione"}),
                    64: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Se scelta, il primo pulsante (rosso) rimanda alla scheda del prodotto.",
                            "label": "Pagina prodotto",
                            "page_type": ["products.ProductPage"],
                            "required": False,
                        },
                    ),
                    65: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Vecchio campo per un solo link: per i PDF usa i Pulsanti qui sotto.",
                            "label": "Link alternativo",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    66: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Testo link", "max_length": 60, "required": False},
                    ),
                    67: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Es. 'Scheda tecnica', 'Manuale', 'Video'",
                            "label": "Testo del pulsante",
                            "max_length": 60,
                        },
                    ),
                    68: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Pagina del sito", "required": False},
                    ),
                    69: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Carica il file in Documenti: resta sul vostro server e si apre in una nuova scheda.",
                            "label": "Documento (PDF)",
                            "required": False,
                        },
                    ),
                    70: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Es. https://… o /contatti",
                            "label": "Oppure un indirizzo",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    71: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("secondary", "Contorno"),
                                ("primary", "Pieno (rosso)"),
                            ],
                            "label": "Aspetto",
                        },
                    ),
                    72: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 67),
                                ("page", 68),
                                ("document", 69),
                                ("url", 70),
                                ("style", 71),
                            ]
                        ],
                        {},
                    ),
                    73: (
                        "wagtail.blocks.ListBlock",
                        (72,),
                        {
                            "help_text": "Quanti ne servono: schede tecniche, manuali, pagine collegate. Trascina per cambiare l'ordine.",
                            "label": "Pulsanti",
                            "required": False,
                        },
                    ),
                    74: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 61),
                                ("name", 62),
                                ("description", 63),
                                ("product", 64),
                                ("link_url", 65),
                                ("link_label", 66),
                                ("buttons", 73),
                            ]
                        ],
                        {},
                    ),
                    75: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Cosa misuriamo",
                            "label": "Titolo",
                            "max_length": 120,
                        },
                    ),
                    76: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Es. 'Inclinazione'",
                            "label": "Grandezza",
                            "max_length": 80,
                        },
                    ),
                    77: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Es. 'mrad', 'µg/m³', 'veic/h'",
                            "label": "Unità",
                            "max_length": 30,
                            "required": False,
                        },
                    ),
                    78: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Nota", "max_length": 160, "required": False},
                    ),
                    79: (
                        "wagtail.blocks.StructBlock",
                        [[("quantity", 76), ("unit", 77), ("note", 78)]],
                        {},
                    ),
                    80: ("wagtail.blocks.ListBlock", (79,), {"label": "Grandezze"}),
                    81: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 75), ("items", 80)]],
                        {},
                    ),
                    82: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Come funziona",
                            "label": "Titolo",
                            "max_length": 120,
                        },
                    ),
                    83: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Titolo", "max_length": 80},
                    ),
                    84: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Testo", "required": False},
                    ),
                    85: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 83), ("text", 84)]],
                        {},
                    ),
                    86: ("wagtail.blocks.ListBlock", (85,), {"label": "Passaggi"}),
                    87: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 82), ("steps", 86)]],
                        {},
                    ),
                    88: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Dispositivi utilizzati",
                            "label": "Titolo",
                            "max_length": 120,
                        },
                    ),
                    89: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["products.ProductPage"]},
                    ),
                    90: ("wagtail.blocks.ListBlock", (89,), {"label": "Prodotti"}),
                    91: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 88), ("products", 90)]],
                        {},
                    ),
                    92: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Casi di successo",
                            "label": "Titolo",
                            "max_length": 120,
                        },
                    ),
                    93: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["casi.CasoSuccessoPage"]},
                    ),
                    94: ("wagtail.blocks.ListBlock", (93,), {"label": "Casi"}),
                    95: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 92), ("cases", 94)]],
                        {},
                    ),
                    96: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Domande frequenti",
                            "label": "Titolo",
                            "max_length": 120,
                            "required": False,
                        },
                    ),
                    97: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Domanda", "max_length": 200},
                    ),
                    98: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "ol", "ul"],
                            "label": "Risposta",
                        },
                    ),
                    99: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 97), ("answer", 98)]],
                        {},
                    ),
                    100: ("wagtail.blocks.ListBlock", (99,), {"label": "Domande"}),
                    101: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 96), ("items", 100)]],
                        {},
                    ),
                    102: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Scrivici",
                            "label": "Titolo",
                            "max_length": 120,
                            "required": False,
                        },
                    ),
                    103: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Testo sopra il modulo", "required": False},
                    ),
                    104: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("contact", "Richiesta di contatto"),
                                (
                                    "partner",
                                    "Proposta di collaborazione (Diventa partner)",
                                ),
                                ("candidate", "Candidatura (Lavora con noi)"),
                                ("quote", "Richiesta di preventivo"),
                            ],
                            "help_text": "Così sai da quale pagina arriva la richiesta.",
                            "label": "Tipo di richiesta",
                        },
                    ),
                    105: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "label": "Chiedi l'azienda",
                            "required": False,
                        },
                    ),
                    106: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "label": "Chiedi il telefono",
                            "required": False,
                        },
                    ),
                    107: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "label": "Chiedi un messaggio",
                            "required": False,
                        },
                    ),
                    108: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "PDF, Word, ODT, RTF o TXT, massimo 10 MB.",
                            "label": "Permetti un allegato (CV o documento)",
                            "required": False,
                        },
                    ),
                    109: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Vuoto = 'Invia richiesta'.",
                            "label": "Testo del pulsante",
                            "max_length": 40,
                            "required": False,
                        },
                    ),
                    110: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Vuoto = 'Richiesta inviata. Ti risponderemo al più presto.'",
                            "label": "Messaggio dopo l'invio",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    111: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 102),
                                ("intro", 103),
                                ("form_type", 104),
                                ("show_company", 105),
                                ("show_phone", 106),
                                ("show_message", 107),
                                ("show_attachment", 108),
                                ("submit_label", 109),
                                ("success_message", 110),
                            ]
                        ],
                        {},
                    ),
                },
                verbose_name="Corpo articolo",
            ),
        ),
    ]
