# Generated by Django 5.2.17 on 2026-10-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_restore_service_cards"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogindexpage",
            name="empty_text",
            field=models.TextField(
                blank=True,
                help_text="Vuoto = testo predefinito. Sotto compaiono i pulsanti verso i casi di successo e i contatti.",
                max_length=400,
                verbose_name="Testo",
            ),
        ),
        migrations.AddField(
            model_name="blogindexpage",
            name="empty_title",
            field=models.CharField(
                blank=True,
                help_text='Vuoto = "Le news arriveranno presto" (tradotto in EN/FR).',
                max_length=120,
                verbose_name="Titolo",
            ),
        ),
    ]
