# Generated by Django 5.2.17 on 2026-10-07 15:03

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_blogindexpage_empty_text_blogindexpage_empty_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogindexpage",
            name="intro",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 6),
                    ("rich_text", 7),
                    ("image", 11),
                    ("quote", 14),
                    ("cta", 19),
                    ("service_cards", 22),
                    ("columns", 24),
                    ("video_embed", 26),
                    ("download", 28),
                    ("spacer", 30),
                    ("stats", 36),
                    ("network_diagram", 37),
                    ("solution_cards", 44),
                    ("feature_grid", 56),
                    ("testimonial", 58),
                    ("partner_logos", 61),
                    ("portfolio_grid", 66),
                    ("text_section", 71),
                    ("product_feature", 85),
                    ("measures", 92),
                    ("steps", 98),
                    ("device_cards", 102),
                    ("case_cards", 106),
                    ("faq", 112),
                    ("contact_form", 122),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "highlight",
                                "link",
                                "color-primary",
                                "color-muted",
                                "color-dark",
                                "font-heading",
                                "font-mono",
                                "size-large",
                            ],
                            "max_length": 120,
                            "required": True,
                        },
                    ),
                    1: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "highlight",
                                "link",
                                "color-primary",
                                "color-muted",
                                "color-dark",
                                "font-heading",
                                "font-mono",
                                "size-large",
                            ],
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    2: ("core.api_blocks.ImageChooserBlock", (), {"required": False}),
                    3: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "highlight",
                                "link",
                                "color-primary",
                                "color-muted",
                                "color-dark",
                                "font-heading",
                                "font-mono",
                                "size-large",
                            ],
                            "max_length": 40,
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 200, "required": False},
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Predefinito"),
                                ("accent", "Accento"),
                                ("muted", "Attenuato"),
                            ],
                            "help_text": "Stile della sezione - usa i colori del tema attivo.",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 0),
                                ("subheading", 1),
                                ("background_image", 2),
                                ("cta_label", 3),
                                ("cta_url", 4),
                                ("variant", 5),
                            ]
                        ],
                        {},
                    ),
                    7: ("core.blocks.RichTextBlock", (), {}),
                    8: ("core.api_blocks.ImageChooserBlock", (), {"required": True}),
                    9: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "highlight",
                                "link",
                                "color-primary",
                                "color-muted",
                                "color-dark",
                                "font-heading",
                                "font-mono",
                                "size-large",
                            ],
                            "max_length": 250,
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 250, "required": False},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 8), ("caption", 9), ("alt_text", 10)]],
                        {},
                    ),
                    12: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "highlight",
                                "link",
                                "color-primary",
                                "color-muted",
                                "color-dark",
                                "font-heading",
                                "font-mono",
                                "size-large",
                            ],
                            "required": True,
                        },
                    ),
                    13: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "highlight",
                                "link",
                                "color-primary",
                                "color-muted",
                                "color-dark",
                                "font-heading",
                                "font-mono",
                                "size-large",
                            ],
                            "max_length": 120,
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 12), ("attribution", 13)]],
                        {},
                    ),
                    15: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "highlight",
                                "link",
                                "color-primary",
                                "color-muted",
                                "color-dark",
                                "font-heading",
                                "font-mono",
                                "size-large",
                            ],
                            "required": False,
                        },
                    ),
                    16: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "default": "Contattaci",
                            "features": [
                                "bold",
                                "italic",
                                "highlight",
                                "link",
                                "color-primary",
                                "color-muted",
                                "color-dark",
                                "font-heading",
                                "font-mono",
                                "size-large",
                            ],
                            "max_length": 40,
                        },
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "/contatti/", "max_length": 200},
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("primary", "Primario"), ("subtle", "Discreto")]},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 0),
                                ("body", 15),
                                ("button_label", 16),
                                ("button_url", 17),
                                ("style", 18),
                            ]
                        ],
                        {},
                    ),
                    20: (
                        "core.api_blocks.PageChooserBlock",
                        (),
                        {"page_type": ["services.ServicePage"]},
                    ),
                    21: ("wagtail.blocks.ListBlock", (20,), {}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("services", 21)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 7), ("image", 11)]],
                        {"required": False},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("left", 23), ("right", 23)]],
                        {},
                    ),
                    25: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "URL YouTube o Vimeo", "required": True},
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("embed", 25), ("caption", 9)]],
                        {},
                    ),
                    27: (
                        "core.api_blocks.DocumentChooserBlock",
                        (),
                        {"required": True},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("document", 27), ("label", 13)]],
                        {},
                    ),
                    29: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Piccolo"),
                                ("md", "Medio"),
                                ("lg", "Grande"),
                            ]
                        },
                    ),
                    30: ("wagtail.blocks.StructBlock", [[("size", 29)]], {}),
                    31: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Numero puro, es. 500 (niente + o testo)"},
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "+", "max_length": 10, "required": False},
                    ),
                    33: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "highlight",
                                "link",
                                "color-primary",
                                "color-muted",
                                "color-dark",
                                "font-heading",
                                "font-mono",
                                "size-large",
                            ],
                            "max_length": 80,
                        },
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("value", 31), ("suffix", 32), ("label", 33)]],
                        {},
                    ),
                    35: ("wagtail.blocks.ListBlock", (34,), {}),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("stats", 35), ("variant", 5)]],
                        {},
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("caption", 9)]],
                        {},
                    ),
                    38: (
                        "core.api_blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Icona SVG/PNG, es. smart-road.svg",
                            "required": False,
                        },
                    ),
                    39: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "highlight",
                                "link",
                                "color-primary",
                                "color-muted",
                                "color-dark",
                                "font-heading",
                                "font-mono",
                                "size-large",
                            ],
                            "max_length": 60,
                        },
                    ),
                    40: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "highlight",
                                "link",
                                "color-primary",
                                "color-muted",
                                "color-dark",
                                "font-heading",
                                "font-mono",
                                "size-large",
                            ],
                            "max_length": 200,
                        },
                    ),
                    41: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "default": "Scopri",
                            "features": [
                                "bold",
                                "italic",
                                "highlight",
                                "link",
                                "color-primary",
                                "color-muted",
                                "color-dark",
                                "font-heading",
                                "font-mono",
                                "size-large",
                            ],
                            "max_length": 40,
                        },
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 38),
                                ("title", 39),
                                ("description", 40),
                                ("link_url", 4),
                                ("link_label", 41),
                            ]
                        ],
                        {},
                    ),
                    43: ("wagtail.blocks.ListBlock", (42,), {}),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("cards", 43)]],
                        {},
                    ),
                    45: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "highlight",
                                "link",
                                "color-primary",
                                "color-muted",
                                "color-dark",
                                "font-heading",
                                "font-mono",
                                "size-large",
                            ],
                            "max_length": 160,
                            "required": False,
                        },
                    ),
                    46: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "label": "Centra titolo e sottotitolo",
                            "required": False,
                        },
                    ),
                    47: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Centra icona, titolo e descrizione di ogni vantaggio.",
                            "label": "Centra il contenuto dei vantaggi",
                            "required": False,
                        },
                    ),
                    48: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("auto", "Automatico"),
                                ("2", "2 per riga"),
                                ("3", "3 per riga"),
                                ("4", "4 per riga"),
                                ("5", "5 per riga"),
                                ("6", "6 per riga"),
                            ],
                            "help_text": "Su tablet e cellulare il numero si riduce da solo per restare leggibile.",
                            "label": "Card per riga",
                            "required": False,
                        },
                    ),
                    49: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("auto", "Predefinita"),
                                ("narrow", "Stretta (720 px)"),
                                ("normal", "Media (1000 px)"),
                                ("wide", "Larga (1280 px)"),
                                ("full", "Intera larghezza disponibile"),
                            ],
                            "label": "Larghezza della sezione",
                            "required": False,
                        },
                    ),
                    50: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("auto", "Predefinito"),
                                ("none", "Nessuno"),
                                ("small", "Piccolo"),
                                ("large", "Grande"),
                            ],
                            "label": "Spazio sopra e sotto",
                            "required": False,
                        },
                    ),
                    51: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("auto", "Predefinito"),
                                ("none", "Nessuno"),
                                ("small", "Piccolo"),
                                ("large", "Grande"),
                            ],
                            "label": "Spazio ai lati",
                            "required": False,
                        },
                    ),
                    52: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("auto", "Predefinita"),
                                ("small", "Piccola"),
                                ("large", "Grande"),
                            ],
                            "label": "Distanza tra i vantaggi",
                            "required": False,
                        },
                    ),
                    53: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("normal", "Normale (1 colonna)"),
                                ("wide", "Largo (2 colonne)"),
                                ("full", "Intera larghezza (100%)"),
                            ],
                            "help_text": "Su cellulare ogni vantaggio occupa comunque tutta la larghezza.",
                            "label": "Larghezza",
                            "required": False,
                        },
                    ),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 2),
                                ("title", 39),
                                ("description", 1),
                                ("width", 53),
                            ]
                        ],
                        {},
                    ),
                    55: ("wagtail.blocks.ListBlock", (54,), {}),
                    56: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 45),
                                ("subheading", 9),
                                ("center_heading", 46),
                                ("center_items", 47),
                                ("columns", 48),
                                ("max_width", 49),
                                ("padding_y", 50),
                                ("padding_x", 51),
                                ("gap", 52),
                                ("features", 55),
                            ]
                        ],
                        {},
                    ),
                    57: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "highlight",
                                "link",
                                "color-primary",
                                "color-muted",
                                "color-dark",
                                "font-heading",
                                "font-mono",
                                "size-large",
                            ],
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    58: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("quote", 12),
                                ("name", 57),
                                ("role", 57),
                                ("avatar", 2),
                                ("variant", 5),
                            ]
                        ],
                        {},
                    ),
                    59: ("core.api_blocks.ImageChooserBlock", (), {}),
                    60: ("wagtail.blocks.ListBlock", (59,), {}),
                    61: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("logos", 60)]],
                        {},
                    ),
                    62: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "default": "Vedi tutto",
                            "features": [
                                "bold",
                                "italic",
                                "highlight",
                                "link",
                                "color-primary",
                                "color-muted",
                                "color-dark",
                                "font-heading",
                                "font-mono",
                                "size-large",
                            ],
                            "max_length": 40,
                        },
                    ),
                    63: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "highlight",
                                "link",
                                "color-primary",
                                "color-muted",
                                "color-dark",
                                "font-heading",
                                "font-mono",
                                "size-large",
                            ],
                            "max_length": 120,
                        },
                    ),
                    64: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 8),
                                ("title", 63),
                                ("client", 13),
                                ("excerpt", 1),
                                ("url", 4),
                            ]
                        ],
                        {},
                    ),
                    65: ("wagtail.blocks.ListBlock", (64,), {}),
                    66: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 13),
                                ("view_all_url", 4),
                                ("view_all_label", 62),
                                ("items", 65),
                            ]
                        ],
                        {},
                    ),
                    67: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Titolo", "max_length": 160},
                    ),
                    68: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "highlight",
                            ],
                            "label": "Testo",
                        },
                    ),
                    69: ("wagtail.blocks.CharBlock", (), {"max_length": 60}),
                    70: (
                        "wagtail.blocks.ListBlock",
                        (69,),
                        {
                            "help_text": "Brevi etichette mostrate come pillole sotto il testo, es. 'Eventi real-time'.",
                            "label": "Punti chiave",
                            "required": False,
                        },
                    ),
                    71: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 67), ("text", 68), ("highlights", 70)]],
                        {},
                    ),
                    72: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Es. 'La soluzione Axatel'",
                            "label": "Etichetta",
                            "max_length": 60,
                            "required": False,
                        },
                    ),
                    73: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Nome prodotto o servizio", "max_length": 120},
                    ),
                    74: ("wagtail.blocks.TextBlock", (), {"label": "Descrizione"}),
                    75: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Se scelta, il primo pulsante (rosso) rimanda alla scheda del prodotto.",
                            "label": "Pagina prodotto",
                            "page_type": ["products.ProductPage"],
                            "required": False,
                        },
                    ),
                    76: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Vecchio campo per un solo link: per i PDF usa i Pulsanti qui sotto.",
                            "label": "Link alternativo",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    77: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Testo link", "max_length": 60, "required": False},
                    ),
                    78: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Es. 'Scheda tecnica', 'Manuale', 'Video'",
                            "label": "Testo del pulsante",
                            "max_length": 60,
                        },
                    ),
                    79: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Pagina del sito", "required": False},
                    ),
                    80: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Carica il file in Documenti: resta sul vostro server e si apre in una nuova scheda.",
                            "label": "Documento (PDF)",
                            "required": False,
                        },
                    ),
                    81: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Es. https://… o /contatti",
                            "label": "Oppure un indirizzo",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    82: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("secondary", "Contorno"),
                                ("primary", "Pieno (rosso)"),
                            ],
                            "label": "Aspetto",
                        },
                    ),
                    83: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 78),
                                ("page", 79),
                                ("document", 80),
                                ("url", 81),
                                ("style", 82),
                            ]
                        ],
                        {},
                    ),
                    84: (
                        "wagtail.blocks.ListBlock",
                        (83,),
                        {
                            "help_text": "Quanti ne servono: schede tecniche, manuali, pagine collegate. Trascina per cambiare l'ordine.",
                            "label": "Pulsanti",
                            "required": False,
                        },
                    ),
                    85: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 72),
                                ("name", 73),
                                ("description", 74),
                                ("product", 75),
                                ("link_url", 76),
                                ("link_label", 77),
                                ("buttons", 84),
                            ]
                        ],
                        {},
                    ),
                    86: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Cosa misuriamo",
                            "label": "Titolo",
                            "max_length": 120,
                        },
                    ),
                    87: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Es. 'Inclinazione'",
                            "label": "Grandezza",
                            "max_length": 80,
                        },
                    ),
                    88: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Es. 'mrad', 'µg/m³', 'veic/h'",
                            "label": "Unità",
                            "max_length": 30,
                            "required": False,
                        },
                    ),
                    89: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Nota", "max_length": 160, "required": False},
                    ),
                    90: (
                        "wagtail.blocks.StructBlock",
                        [[("quantity", 87), ("unit", 88), ("note", 89)]],
                        {},
                    ),
                    91: ("wagtail.blocks.ListBlock", (90,), {"label": "Grandezze"}),
                    92: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 86), ("items", 91)]],
                        {},
                    ),
                    93: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Come funziona",
                            "label": "Titolo",
                            "max_length": 120,
                        },
                    ),
                    94: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Titolo", "max_length": 80},
                    ),
                    95: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Testo", "required": False},
                    ),
                    96: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 94), ("text", 95)]],
                        {},
                    ),
                    97: ("wagtail.blocks.ListBlock", (96,), {"label": "Passaggi"}),
                    98: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 93), ("steps", 97)]],
                        {},
                    ),
                    99: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Dispositivi utilizzati",
                            "label": "Titolo",
                            "max_length": 120,
                        },
                    ),
                    100: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["products.ProductPage"]},
                    ),
                    101: ("wagtail.blocks.ListBlock", (100,), {"label": "Prodotti"}),
                    102: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 99), ("products", 101)]],
                        {},
                    ),
                    103: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Casi di successo",
                            "label": "Titolo",
                            "max_length": 120,
                        },
                    ),
                    104: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["casi.CasoSuccessoPage"]},
                    ),
                    105: ("wagtail.blocks.ListBlock", (104,), {"label": "Casi"}),
                    106: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 103), ("cases", 105)]],
                        {},
                    ),
                    107: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Domande frequenti",
                            "label": "Titolo",
                            "max_length": 120,
                            "required": False,
                        },
                    ),
                    108: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Domanda", "max_length": 200},
                    ),
                    109: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "ol", "ul"],
                            "label": "Risposta",
                        },
                    ),
                    110: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 108), ("answer", 109)]],
                        {},
                    ),
                    111: ("wagtail.blocks.ListBlock", (110,), {"label": "Domande"}),
                    112: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 107), ("items", 111)]],
                        {},
                    ),
                    113: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Scrivici",
                            "label": "Titolo",
                            "max_length": 120,
                            "required": False,
                        },
                    ),
                    114: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Testo sopra il modulo", "required": False},
                    ),
                    115: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("contact", "Richiesta di contatto"),
                                (
                                    "partner",
                                    "Proposta di collaborazione (Diventa partner)",
                                ),
                                ("candidate", "Candidatura (Lavora con noi)"),
                                ("quote", "Richiesta di preventivo"),
                            ],
                            "help_text": "Così sai da quale pagina arriva la richiesta.",
                            "label": "Tipo di richiesta",
                        },
                    ),
                    116: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "label": "Chiedi l'azienda",
                            "required": False,
                        },
                    ),
                    117: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "label": "Chiedi il telefono",
                            "required": False,
                        },
                    ),
                    118: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "label": "Chiedi un messaggio",
                            "required": False,
                        },
                    ),
                    119: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "PDF, Word, ODT, RTF o TXT, massimo 10 MB.",
                            "label": "Permetti un allegato (CV o documento)",
                            "required": False,
                        },
                    ),
                    120: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Vuoto = 'Invia richiesta'.",
                            "label": "Testo del pulsante",
                            "max_length": 40,
                            "required": False,
                        },
                    ),
                    121: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Vuoto = 'Richiesta inviata. Ti risponderemo al più presto.'",
                            "label": "Messaggio dopo l'invio",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    122: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 113),
                                ("intro", 114),
                                ("form_type", 115),
                                ("show_company", 116),
                                ("show_phone", 117),
                                ("show_message", 118),
                                ("show_attachment", 119),
                                ("submit_label", 120),
                                ("success_message", 121),
                            ]
                        ],
                        {},
                    ),
                },
                verbose_name="Introduzione blog",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 6),
                    ("rich_text", 7),
                    ("image", 11),
                    ("quote", 14),
                    ("cta", 19),
                    ("service_cards", 22),
                    ("columns", 24),
                    ("video_embed", 26),
                    ("download", 28),
                    ("spacer", 30),
                    ("stats", 36),
                    ("network_diagram", 37),
                    ("solution_cards", 44),
                    ("feature_grid", 56),
                    ("testimonial", 58),
                    ("partner_logos", 61),
                    ("portfolio_grid", 66),
                    ("text_section", 71),
                    ("product_feature", 85),
                    ("measures", 92),
                    ("steps", 98),
                    ("device_cards", 102),
                    ("case_cards", 106),
                    ("faq", 112),
                    ("contact_form", 122),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "highlight",
                                "link",
                                "color-primary",
                                "color-muted",
                                "color-dark",
                                "font-heading",
                                "font-mono",
                                "size-large",
                            ],
                            "max_length": 120,
                            "required": True,
                        },
                    ),
                    1: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "highlight",
                                "link",
                                "color-primary",
                                "color-muted",
                                "color-dark",
                                "font-heading",
                                "font-mono",
                                "size-large",
                            ],
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    2: ("core.api_blocks.ImageChooserBlock", (), {"required": False}),
                    3: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "highlight",
                                "link",
                                "color-primary",
                                "color-muted",
                                "color-dark",
                                "font-heading",
                                "font-mono",
                                "size-large",
                            ],
                            "max_length": 40,
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 200, "required": False},
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Predefinito"),
                                ("accent", "Accento"),
                                ("muted", "Attenuato"),
                            ],
                            "help_text": "Stile della sezione - usa i colori del tema attivo.",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 0),
                                ("subheading", 1),
                                ("background_image", 2),
                                ("cta_label", 3),
                                ("cta_url", 4),
                                ("variant", 5),
                            ]
                        ],
                        {},
                    ),
                    7: ("core.blocks.RichTextBlock", (), {}),
                    8: ("core.api_blocks.ImageChooserBlock", (), {"required": True}),
                    9: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "highlight",
                                "link",
                                "color-primary",
                                "color-muted",
                                "color-dark",
                                "font-heading",
                                "font-mono",
                                "size-large",
                            ],
                            "max_length": 250,
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 250, "required": False},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 8), ("caption", 9), ("alt_text", 10)]],
                        {},
                    ),
                    12: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "highlight",
                                "link",
                                "color-primary",
                                "color-muted",
                                "color-dark",
                                "font-heading",
                                "font-mono",
                                "size-large",
                            ],
                            "required": True,
                        },
                    ),
                    13: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "highlight",
                                "link",
                                "color-primary",
                                "color-muted",
                                "color-dark",
                                "font-heading",
                                "font-mono",
                                "size-large",
                            ],
                            "max_length": 120,
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 12), ("attribution", 13)]],
                        {},
                    ),
                    15: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "highlight",
                                "link",
                                "color-primary",
                                "color-muted",
                                "color-dark",
                                "font-heading",
                                "font-mono",
                                "size-large",
                            ],
                            "required": False,
                        },
                    ),
                    16: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "default": "Contattaci",
                            "features": [
                                "bold",
                                "italic",
                                "highlight",
                                "link",
                                "color-primary",
                                "color-muted",
                                "color-dark",
                                "font-heading",
                                "font-mono",
                                "size-large",
                            ],
                            "max_length": 40,
                        },
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "/contatti/", "max_length": 200},
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("primary", "Primario"), ("subtle", "Discreto")]},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 0),
                                ("body", 15),
                                ("button_label", 16),
                                ("button_url", 17),
                                ("style", 18),
                            ]
                        ],
                        {},
                    ),
                    20: (
                        "core.api_blocks.PageChooserBlock",
                        (),
                        {"page_type": ["services.ServicePage"]},
                    ),
                    21: ("wagtail.blocks.ListBlock", (20,), {}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("services", 21)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 7), ("image", 11)]],
                        {"required": False},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("left", 23), ("right", 23)]],
                        {},
                    ),
                    25: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"help_text": "URL YouTube o Vimeo", "required": True},
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("embed", 25), ("caption", 9)]],
                        {},
                    ),
                    27: (
                        "core.api_blocks.DocumentChooserBlock",
                        (),
                        {"required": True},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("document", 27), ("label", 13)]],
                        {},
                    ),
                    29: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Piccolo"),
                                ("md", "Medio"),
                                ("lg", "Grande"),
                            ]
                        },
                    ),
                    30: ("wagtail.blocks.StructBlock", [[("size", 29)]], {}),
                    31: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"help_text": "Numero puro, es. 500 (niente + o testo)"},
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "+", "max_length": 10, "required": False},
                    ),
                    33: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "highlight",
                                "link",
                                "color-primary",
                                "color-muted",
                                "color-dark",
                                "font-heading",
                                "font-mono",
                                "size-large",
                            ],
                            "max_length": 80,
                        },
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("value", 31), ("suffix", 32), ("label", 33)]],
                        {},
                    ),
                    35: ("wagtail.blocks.ListBlock", (34,), {}),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("stats", 35), ("variant", 5)]],
                        {},
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("caption", 9)]],
                        {},
                    ),
                    38: (
                        "core.api_blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Icona SVG/PNG, es. smart-road.svg",
                            "required": False,
                        },
                    ),
                    39: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "highlight",
                                "link",
                                "color-primary",
                                "color-muted",
                                "color-dark",
                                "font-heading",
                                "font-mono",
                                "size-large",
                            ],
                            "max_length": 60,
                        },
                    ),
                    40: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "highlight",
                                "link",
                                "color-primary",
                                "color-muted",
                                "color-dark",
                                "font-heading",
                                "font-mono",
                                "size-large",
                            ],
                            "max_length": 200,
                        },
                    ),
                    41: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "default": "Scopri",
                            "features": [
                                "bold",
                                "italic",
                                "highlight",
                                "link",
                                "color-primary",
                                "color-muted",
                                "color-dark",
                                "font-heading",
                                "font-mono",
                                "size-large",
                            ],
                            "max_length": 40,
                        },
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 38),
                                ("title", 39),
                                ("description", 40),
                                ("link_url", 4),
                                ("link_label", 41),
                            ]
                        ],
                        {},
                    ),
                    43: ("wagtail.blocks.ListBlock", (42,), {}),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("cards", 43)]],
                        {},
                    ),
                    45: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "highlight",
                                "link",
                                "color-primary",
                                "color-muted",
                                "color-dark",
                                "font-heading",
                                "font-mono",
                                "size-large",
                            ],
                            "max_length": 160,
                            "required": False,
                        },
                    ),
                    46: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "label": "Centra titolo e sottotitolo",
                            "required": False,
                        },
                    ),
                    47: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Centra icona, titolo e descrizione di ogni vantaggio.",
                            "label": "Centra il contenuto dei vantaggi",
                            "required": False,
                        },
                    ),
                    48: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("auto", "Automatico"),
                                ("2", "2 per riga"),
                                ("3", "3 per riga"),
                                ("4", "4 per riga"),
                                ("5", "5 per riga"),
                                ("6", "6 per riga"),
                            ],
                            "help_text": "Su tablet e cellulare il numero si riduce da solo per restare leggibile.",
                            "label": "Card per riga",
                            "required": False,
                        },
                    ),
                    49: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("auto", "Predefinita"),
                                ("narrow", "Stretta (720 px)"),
                                ("normal", "Media (1000 px)"),
                                ("wide", "Larga (1280 px)"),
                                ("full", "Intera larghezza disponibile"),
                            ],
                            "label": "Larghezza della sezione",
                            "required": False,
                        },
                    ),
                    50: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("auto", "Predefinito"),
                                ("none", "Nessuno"),
                                ("small", "Piccolo"),
                                ("large", "Grande"),
                            ],
                            "label": "Spazio sopra e sotto",
                            "required": False,
                        },
                    ),
                    51: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("auto", "Predefinito"),
                                ("none", "Nessuno"),
                                ("small", "Piccolo"),
                                ("large", "Grande"),
                            ],
                            "label": "Spazio ai lati",
                            "required": False,
                        },
                    ),
                    52: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("auto", "Predefinita"),
                                ("small", "Piccola"),
                                ("large", "Grande"),
                            ],
                            "label": "Distanza tra i vantaggi",
                            "required": False,
                        },
                    ),
                    53: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("normal", "Normale (1 colonna)"),
                                ("wide", "Largo (2 colonne)"),
                                ("full", "Intera larghezza (100%)"),
                            ],
                            "help_text": "Su cellulare ogni vantaggio occupa comunque tutta la larghezza.",
                            "label": "Larghezza",
                            "required": False,
                        },
                    ),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("icon", 2),
                                ("title", 39),
                                ("description", 1),
                                ("width", 53),
                            ]
                        ],
                        {},
                    ),
                    55: ("wagtail.blocks.ListBlock", (54,), {}),
                    56: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 45),
                                ("subheading", 9),
                                ("center_heading", 46),
                                ("center_items", 47),
                                ("columns", 48),
                                ("max_width", 49),
                                ("padding_y", 50),
                                ("padding_x", 51),
                                ("gap", 52),
                                ("features", 55),
                            ]
                        ],
                        {},
                    ),
                    57: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "highlight",
                                "link",
                                "color-primary",
                                "color-muted",
                                "color-dark",
                                "font-heading",
                                "font-mono",
                                "size-large",
                            ],
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    58: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("quote", 12),
                                ("name", 57),
                                ("role", 57),
                                ("avatar", 2),
                                ("variant", 5),
                            ]
                        ],
                        {},
                    ),
                    59: ("core.api_blocks.ImageChooserBlock", (), {}),
                    60: ("wagtail.blocks.ListBlock", (59,), {}),
                    61: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("logos", 60)]],
                        {},
                    ),
                    62: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "default": "Vedi tutto",
                            "features": [
                                "bold",
                                "italic",
                                "highlight",
                                "link",
                                "color-primary",
                                "color-muted",
                                "color-dark",
                                "font-heading",
                                "font-mono",
                                "size-large",
                            ],
                            "max_length": 40,
                        },
                    ),
                    63: (
                        "core.blocks_shared.ExpandedRichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "highlight",
                                "link",
                                "color-primary",
                                "color-muted",
                                "color-dark",
                                "font-heading",
                                "font-mono",
                                "size-large",
                            ],
                            "max_length": 120,
                        },
                    ),
                    64: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 8),
                                ("title", 63),
                                ("client", 13),
                                ("excerpt", 1),
                                ("url", 4),
                            ]
                        ],
                        {},
                    ),
                    65: ("wagtail.blocks.ListBlock", (64,), {}),
                    66: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 13),
                                ("view_all_url", 4),
                                ("view_all_label", 62),
                                ("items", 65),
                            ]
                        ],
                        {},
                    ),
                    67: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Titolo", "max_length": 160},
                    ),
                    68: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "highlight",
                            ],
                            "label": "Testo",
                        },
                    ),
                    69: ("wagtail.blocks.CharBlock", (), {"max_length": 60}),
                    70: (
                        "wagtail.blocks.ListBlock",
                        (69,),
                        {
                            "help_text": "Brevi etichette mostrate come pillole sotto il testo, es. 'Eventi real-time'.",
                            "label": "Punti chiave",
                            "required": False,
                        },
                    ),
                    71: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 67), ("text", 68), ("highlights", 70)]],
                        {},
                    ),
                    72: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Es. 'La soluzione Axatel'",
                            "label": "Etichetta",
                            "max_length": 60,
                            "required": False,
                        },
                    ),
                    73: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Nome prodotto o servizio", "max_length": 120},
                    ),
                    74: ("wagtail.blocks.TextBlock", (), {"label": "Descrizione"}),
                    75: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Se scelta, il primo pulsante (rosso) rimanda alla scheda del prodotto.",
                            "label": "Pagina prodotto",
                            "page_type": ["products.ProductPage"],
                            "required": False,
                        },
                    ),
                    76: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Vecchio campo per un solo link: per i PDF usa i Pulsanti qui sotto.",
                            "label": "Link alternativo",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    77: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Testo link", "max_length": 60, "required": False},
                    ),
                    78: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Es. 'Scheda tecnica', 'Manuale', 'Video'",
                            "label": "Testo del pulsante",
                            "max_length": 60,
                        },
                    ),
                    79: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Pagina del sito", "required": False},
                    ),
                    80: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Carica il file in Documenti: resta sul vostro server e si apre in una nuova scheda.",
                            "label": "Documento (PDF)",
                            "required": False,
                        },
                    ),
                    81: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Es. https://… o /contatti",
                            "label": "Oppure un indirizzo",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    82: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("secondary", "Contorno"),
                                ("primary", "Pieno (rosso)"),
                            ],
                            "label": "Aspetto",
                        },
                    ),
                    83: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 78),
                                ("page", 79),
                                ("document", 80),
                                ("url", 81),
                                ("style", 82),
                            ]
                        ],
                        {},
                    ),
                    84: (
                        "wagtail.blocks.ListBlock",
                        (83,),
                        {
                            "help_text": "Quanti ne servono: schede tecniche, manuali, pagine collegate. Trascina per cambiare l'ordine.",
                            "label": "Pulsanti",
                            "required": False,
                        },
                    ),
                    85: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("label", 72),
                                ("name", 73),
                                ("description", 74),
                                ("product", 75),
                                ("link_url", 76),
                                ("link_label", 77),
                                ("buttons", 84),
                            ]
                        ],
                        {},
                    ),
                    86: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Cosa misuriamo",
                            "label": "Titolo",
                            "max_length": 120,
                        },
                    ),
                    87: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Es. 'Inclinazione'",
                            "label": "Grandezza",
                            "max_length": 80,
                        },
                    ),
                    88: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Es. 'mrad', 'µg/m³', 'veic/h'",
                            "label": "Unità",
                            "max_length": 30,
                            "required": False,
                        },
                    ),
                    89: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Nota", "max_length": 160, "required": False},
                    ),
                    90: (
                        "wagtail.blocks.StructBlock",
                        [[("quantity", 87), ("unit", 88), ("note", 89)]],
                        {},
                    ),
                    91: ("wagtail.blocks.ListBlock", (90,), {"label": "Grandezze"}),
                    92: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 86), ("items", 91)]],
                        {},
                    ),
                    93: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Come funziona",
                            "label": "Titolo",
                            "max_length": 120,
                        },
                    ),
                    94: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Titolo", "max_length": 80},
                    ),
                    95: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Testo", "required": False},
                    ),
                    96: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 94), ("text", 95)]],
                        {},
                    ),
                    97: ("wagtail.blocks.ListBlock", (96,), {"label": "Passaggi"}),
                    98: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 93), ("steps", 97)]],
                        {},
                    ),
                    99: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Dispositivi utilizzati",
                            "label": "Titolo",
                            "max_length": 120,
                        },
                    ),
                    100: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["products.ProductPage"]},
                    ),
                    101: ("wagtail.blocks.ListBlock", (100,), {"label": "Prodotti"}),
                    102: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 99), ("products", 101)]],
                        {},
                    ),
                    103: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Casi di successo",
                            "label": "Titolo",
                            "max_length": 120,
                        },
                    ),
                    104: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["casi.CasoSuccessoPage"]},
                    ),
                    105: ("wagtail.blocks.ListBlock", (104,), {"label": "Casi"}),
                    106: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 103), ("cases", 105)]],
                        {},
                    ),
                    107: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Domande frequenti",
                            "label": "Titolo",
                            "max_length": 120,
                            "required": False,
                        },
                    ),
                    108: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Domanda", "max_length": 200},
                    ),
                    109: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "link", "ol", "ul"],
                            "label": "Risposta",
                        },
                    ),
                    110: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 108), ("answer", 109)]],
                        {},
                    ),
                    111: ("wagtail.blocks.ListBlock", (110,), {"label": "Domande"}),
                    112: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 107), ("items", 111)]],
                        {},
                    ),
                    113: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Scrivici",
                            "label": "Titolo",
                            "max_length": 120,
                            "required": False,
                        },
                    ),
                    114: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Testo sopra il modulo", "required": False},
                    ),
                    115: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("contact", "Richiesta di contatto"),
                                (
                                    "partner",
                                    "Proposta di collaborazione (Diventa partner)",
                                ),
                                ("candidate", "Candidatura (Lavora con noi)"),
                                ("quote", "Richiesta di preventivo"),
                            ],
                            "help_text": "Così sai da quale pagina arriva la richiesta.",
                            "label": "Tipo di richiesta",
                        },
                    ),
                    116: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "label": "Chiedi l'azienda",
                            "required": False,
                        },
                    ),
                    117: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "label": "Chiedi il telefono",
                            "required": False,
                        },
                    ),
                    118: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "label": "Chiedi un messaggio",
                            "required": False,
                        },
                    ),
                    119: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "PDF, Word, ODT, RTF o TXT, massimo 10 MB.",
                            "label": "Permetti un allegato (CV o documento)",
                            "required": False,
                        },
                    ),
                    120: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Vuoto = 'Invia richiesta'.",
                            "label": "Testo del pulsante",
                            "max_length": 40,
                            "required": False,
                        },
                    ),
                    121: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Vuoto = 'Richiesta inviata. Ti risponderemo al più presto.'",
                            "label": "Messaggio dopo l'invio",
                            "max_length": 200,
                            "required": False,
                        },
                    ),
                    122: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 113),
                                ("intro", 114),
                                ("form_type", 115),
                                ("show_company", 116),
                                ("show_phone", 117),
                                ("show_message", 118),
                                ("show_attachment", 119),
                                ("submit_label", 120),
                                ("success_message", 121),
                            ]
                        ],
                        {},
                    ),
                },
                verbose_name="Corpo articolo",
            ),
        ),
    ]
