# Generated by Django 5.2.16 on 2026-07-29 20:38

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_flexpage_body_alter_homepage_body'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_cases_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo hero'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_frasi',
            field=wagtail.fields.StreamField([('frase', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Una frase della rotazione. Usa \\n per forzare un a capo.', 'max_length': 200})}, verbose_name='Frasi rotanti hero'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_quote_text',
            field=models.TextField(blank=True, help_text="Citazione mostrata nell'hero. Le righe vuote separano il testo dalla firma (nome e ruolo).", verbose_name='Citazione hero'),
        ),
    ]
