# Generated by Django 5.2.17 on 2026-09-27 19:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_flexpage_body_alter_homepage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="trust_certifications",
            field=wagtail.fields.StreamField(
                [("logo", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Mostrato come testo se manca il logo; usato anche come testo alternativo.",
                            "label": "Nome",
                            "max_length": 120,
                        },
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Logo", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Link (facoltativo)", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 0), ("logo", 1), ("url", 2)]],
                        {},
                    ),
                },
                help_text="Es. ISO 9001, LoRa Alliance. Solo certificazioni effettivamente ottenute.",
                verbose_name="Certificazioni e riconoscimenti",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="trust_clients",
            field=wagtail.fields.StreamField(
                [("logo", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Mostrato come testo se manca il logo; usato anche come testo alternativo.",
                            "label": "Nome",
                            "max_length": 120,
                        },
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Logo", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Link (facoltativo)", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 0), ("logo", 1), ("url", 2)]],
                        {},
                    ),
                },
                help_text="Loghi di clienti o partner (solo con il loro consenso).",
                verbose_name="Clienti e partner",
            ),
        ),
    ]
