# Generated by Django 5.2.17 on 2026-10-07 15:05

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_block_options"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="infopage",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="Etichetta mostrata sopra il titolo nella pagina e nella card, es. 'Ambiente', 'Piattaforma', 'Azienda'. Vuoto = nessuna etichetta.",
                max_length=100,
                verbose_name="Categoria",
            ),
        ),
        migrations.AddField(
            model_name="infopage",
            name="cover_position",
            field=models.CharField(
                choices=[
                    ("side", "Accanto all'introduzione"),
                    ("top", "Grande, in apertura (come nei casi di successo)"),
                    ("hidden", "Non mostrarla nella pagina (solo nella card)"),
                ],
                default="side",
                help_text="Dove compare l'immagine di copertina nella pagina. Nella card dell'elenco compare comunque.",
                max_length=10,
                verbose_name="Immagine nella pagina",
            ),
        ),
        migrations.AlterField(
            model_name="infopage",
            name="cover_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Immagine di copertina",
            ),
        ),
        migrations.CreateModel(
            name="InfoPageTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_items",
                        to="home.infopage",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="taggit.tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="infopage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="home.InfoPageTag",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
