# Generated by Django 5.2.17 on 2026-10-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0010_block_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoringpage",
            name="cover_position",
            field=models.CharField(
                choices=[
                    ("side", "Accanto all'introduzione"),
                    ("top", "Grande, in apertura (come nei casi di successo)"),
                    ("hidden", "Non mostrarla nella pagina (solo nella card)"),
                ],
                default="side",
                help_text="Dove compare l'immagine di copertina nella pagina. Nella card dell'elenco compare comunque.",
                max_length=10,
                verbose_name="Immagine nella pagina",
            ),
        ),
        migrations.AddField(
            model_name="monitoringpage",
            name="show_card_title",
            field=models.BooleanField(
                default=True,
                help_text="Spegni se l'immagine di copertina contiene già il titolo. Senza immagine il titolo resta sempre visibile.",
                verbose_name="Mostra titolo nella card",
            ),
        ),
        migrations.AlterField(
            model_name="monitoringpage",
            name="short_description",
            field=models.TextField(
                blank=True,
                help_text="Testo mostrato nella card dell'elenco. Usato anche come descrizione per Google se il tab Promuovi è vuoto.",
                max_length=700,
                verbose_name="Descrizione (card)",
            ),
        ),
    ]
