# Generated by Django 5.2.17 on 2026-10-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0007_restore_service_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionpage',
            name='short_description',
            field=models.TextField(blank=True, help_text="Testo mostrato nella card sull'indice. Usato anche come meta description se non specificata nel tab Promuovi.", max_length=700, verbose_name='Descrizione breve (card)'),
        ),
    ]
