# Generated by Django 5.2.17 on 2026-10-03 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProtectedTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        help_text="Esattamente come è scritto, es. 'Angel River', 'LoRaWAN'.",
                        max_length=80,
                        unique=True,
                        verbose_name="Termine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Termine da non tradurre",
                "verbose_name_plural": "Termini da non tradurre",
                "ordering": ["term"],
            },
        ),
        migrations.CreateModel(
            name="TranslationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "languages",
                    models.CharField(
                        default="en,fr", max_length=20, verbose_name="Lingue"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "In coda"),
                            ("running", "In corso"),
                            ("done", "Fatta"),
                            ("failed", "Errore"),
                        ],
                        default="queued",
                        max_length=10,
                        verbose_name="Stato",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Richiesta il"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finita il"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Esito")),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailcore.page",
                        verbose_name="Pagina",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Richiesta da",
                    ),
                ),
            ],
            options={
                "verbose_name": "Traduzione richiesta",
                "verbose_name_plural": "Traduzioni richieste",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TranslationMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_hash",
                    models.CharField(db_index=True, editable=False, max_length=64),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "Inglese"), ("fr", "Francese")],
                        max_length=5,
                        verbose_name="Lingua",
                    ),
                ),
                ("source", models.TextField(verbose_name="Testo italiano")),
                ("target", models.TextField(verbose_name="Traduzione")),
                (
                    "engine",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=80,
                        verbose_name="Modello",
                    ),
                ),
                (
                    "edited",
                    models.BooleanField(
                        default=False,
                        help_text="Spunta dopo aver corretto la traduzione: verrà usata sempre, anche nelle prossime traduzioni.",
                        verbose_name="Corretta a mano",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Memoria di traduzione",
                "verbose_name_plural": "Memoria di traduzione",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_hash", "language"), name="unique_tm_entry"
                    )
                ],
            },
        ),
    ]
