# Generated by Django 5.2.17 on 2026-10-04 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translation", "0002_glossary"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.AddField(
            model_name="translationjob",
            name="publish",
            field=models.BooleanField(
                default=False,
                help_text="Sì = la traduzione va online senza revisione.",
                verbose_name="Pubblica subito",
            ),
        ),
        migrations.CreateModel(
            name="TranslationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auto_translate",
                    models.BooleanField(
                        default=False,
                        help_text="Ogni volta che pubblichi una pagina italiana, la sua versione inglese e francese viene tradotta entro un paio di minuti.",
                        verbose_name="Traduci automaticamente",
                    ),
                ),
                (
                    "auto_publish",
                    models.BooleanField(
                        default=False,
                        help_text="Sì = le traduzioni vanno online senza revisione. No = restano bozze da rileggere e pubblicare. Le correzioni fatte nella Memoria di traduzione vengono sempre riusate.",
                        verbose_name="Pubblica subito le traduzioni",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Traduzione automatica",
            },
        ),
    ]
